// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/header/device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *int32                 `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	Build         *int32                 `protobuf:"varint,2,opt,name=build" json:"build,omitempty"`
	Buvid         *string                `protobuf:"bytes,3,opt,name=buvid" json:"buvid,omitempty"`
	MobiApp       *string                `protobuf:"bytes,4,opt,name=mobiApp" json:"mobiApp,omitempty"`
	Platform      *string                `protobuf:"bytes,5,opt,name=platform" json:"platform,omitempty"`
	Device        *string                `protobuf:"bytes,6,opt,name=device" json:"device,omitempty"`
	Channel       *string                `protobuf:"bytes,7,opt,name=channel" json:"channel,omitempty"`
	Brand         *string                `protobuf:"bytes,8,opt,name=brand" json:"brand,omitempty"`
	Model         *string                `protobuf:"bytes,9,opt,name=model" json:"model,omitempty"`
	Osver         *string                `protobuf:"bytes,10,opt,name=osver" json:"osver,omitempty"`
	FpLocal       *string                `protobuf:"bytes,11,opt,name=fpLocal" json:"fpLocal,omitempty"`
	FpRemote      *string                `protobuf:"bytes,12,opt,name=fpRemote" json:"fpRemote,omitempty"`
	VersionName   *string                `protobuf:"bytes,13,opt,name=versionName" json:"versionName,omitempty"`
	Fp            *string                `protobuf:"bytes,14,opt,name=fp" json:"fp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_app_header_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_header_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_app_header_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetAppId() int32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *Device) GetBuild() int32 {
	if x != nil && x.Build != nil {
		return *x.Build
	}
	return 0
}

func (x *Device) GetBuvid() string {
	if x != nil && x.Buvid != nil {
		return *x.Buvid
	}
	return ""
}

func (x *Device) GetMobiApp() string {
	if x != nil && x.MobiApp != nil {
		return *x.MobiApp
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *Device) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *Device) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *Device) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Device) GetOsver() string {
	if x != nil && x.Osver != nil {
		return *x.Osver
	}
	return ""
}

func (x *Device) GetFpLocal() string {
	if x != nil && x.FpLocal != nil {
		return *x.FpLocal
	}
	return ""
}

func (x *Device) GetFpRemote() string {
	if x != nil && x.FpRemote != nil {
		return *x.FpRemote
	}
	return ""
}

func (x *Device) GetVersionName() string {
	if x != nil && x.VersionName != nil {
		return *x.VersionName
	}
	return ""
}

func (x *Device) GetFp() string {
	if x != nil && x.Fp != nil {
		return *x.Fp
	}
	return ""
}

var File_proto_app_header_device_proto protoreflect.FileDescriptor

const file_proto_app_header_device_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/app/header/device.proto\x12\x06bbdown\"\xdc\x02\n" +
	"\x06Device\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\x05R\x05appId\x12\x14\n" +
	"\x05build\x18\x02 \x01(\x05R\x05build\x12\x14\n" +
	"\x05buvid\x18\x03 \x01(\tR\x05buvid\x12\x18\n" +
	"\amobiApp\x18\x04 \x01(\tR\amobiApp\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x14\n" +
	"\x05osver\x18\n" +
	" \x01(\tR\x05osver\x12\x18\n" +
	"\afpLocal\x18\v \x01(\tR\afpLocal\x12\x1a\n" +
	"\bfpRemote\x18\f \x01(\tR\bfpRemote\x12 \n" +
	"\vversionName\x18\r \x01(\tR\vversionName\x12\x0e\n" +
	"\x02fp\x18\x0e \x01(\tR\x02fpB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_header_device_proto_rawDescOnce sync.Once
	file_proto_app_header_device_proto_rawDescData []byte
)

func file_proto_app_header_device_proto_rawDescGZIP() []byte {
	file_proto_app_header_device_proto_rawDescOnce.Do(func() {
		file_proto_app_header_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_header_device_proto_rawDesc), len(file_proto_app_header_device_proto_rawDesc)))
	})
	return file_proto_app_header_device_proto_rawDescData
}

var file_proto_app_header_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_header_device_proto_goTypes = []any{
	(*Device)(nil), // 0: bbdown.Device
}
var file_proto_app_header_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_header_device_proto_init() }
func file_proto_app_header_device_proto_init() {
	if File_proto_app_header_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_header_device_proto_rawDesc), len(file_proto_app_header_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_header_device_proto_goTypes,
		DependencyIndexes: file_proto_app_header_device_proto_depIdxs,
		MessageInfos:      file_proto_app_header_device_proto_msgTypes,
	}.Build()
	File_proto_app_header_device_proto = out.File
	file_proto_app_header_device_proto_goTypes = nil
	file_proto_app_header_device_proto_depIdxs = nil
}
