// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/response/dmviewreply.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmViewReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Closed          *bool                  `protobuf:"varint,1,opt,name=closed" json:"closed,omitempty"`
	Mask            *VideoMask             `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
	Subtitle        *VideoSubtitle         `protobuf:"bytes,3,opt,name=subtitle" json:"subtitle,omitempty"`
	SpecialDms      []string               `protobuf:"bytes,4,rep,name=specialDms" json:"specialDms,omitempty"`
	AiFlag          *DanmakuFlagConfig     `protobuf:"bytes,5,opt,name=aiFlag" json:"aiFlag,omitempty"`
	PlayerConfig    *DanmuPlayerViewConfig `protobuf:"bytes,6,opt,name=playerConfig" json:"playerConfig,omitempty"`
	SendBoxStyle    *int32                 `protobuf:"varint,7,opt,name=sendBoxStyle" json:"sendBoxStyle,omitempty"`
	Allow           *bool                  `protobuf:"varint,8,opt,name=allow" json:"allow,omitempty"`
	CheckBoxShowMsg *string                `protobuf:"bytes,9,opt,name=checkBoxShowMsg" json:"checkBoxShowMsg,omitempty"`
	CheckBox        *bool                  `protobuf:"varint,10,opt,name=checkBox" json:"checkBox,omitempty"`
	TextPlaceholder *string                `protobuf:"bytes,11,opt,name=textPlaceholder" json:"textPlaceholder,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DmViewReply) Reset() {
	*x = DmViewReply{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmViewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmViewReply) ProtoMessage() {}

func (x *DmViewReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmViewReply.ProtoReflect.Descriptor instead.
func (*DmViewReply) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{0}
}

func (x *DmViewReply) GetClosed() bool {
	if x != nil && x.Closed != nil {
		return *x.Closed
	}
	return false
}

func (x *DmViewReply) GetMask() *VideoMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *DmViewReply) GetSubtitle() *VideoSubtitle {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *DmViewReply) GetSpecialDms() []string {
	if x != nil {
		return x.SpecialDms
	}
	return nil
}

func (x *DmViewReply) GetAiFlag() *DanmakuFlagConfig {
	if x != nil {
		return x.AiFlag
	}
	return nil
}

func (x *DmViewReply) GetPlayerConfig() *DanmuPlayerViewConfig {
	if x != nil {
		return x.PlayerConfig
	}
	return nil
}

func (x *DmViewReply) GetSendBoxStyle() int32 {
	if x != nil && x.SendBoxStyle != nil {
		return *x.SendBoxStyle
	}
	return 0
}

func (x *DmViewReply) GetAllow() bool {
	if x != nil && x.Allow != nil {
		return *x.Allow
	}
	return false
}

func (x *DmViewReply) GetCheckBoxShowMsg() string {
	if x != nil && x.CheckBoxShowMsg != nil {
		return *x.CheckBoxShowMsg
	}
	return ""
}

func (x *DmViewReply) GetCheckBox() bool {
	if x != nil && x.CheckBox != nil {
		return *x.CheckBox
	}
	return false
}

func (x *DmViewReply) GetTextPlaceholder() string {
	if x != nil && x.TextPlaceholder != nil {
		return *x.TextPlaceholder
	}
	return ""
}

type VideoMask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           *int64                 `protobuf:"varint,1,opt,name=cid" json:"cid,omitempty"`
	Plat          *int32                 `protobuf:"varint,2,opt,name=plat" json:"plat,omitempty"`
	Fps           *int32                 `protobuf:"varint,3,opt,name=fps" json:"fps,omitempty"`
	Time          *int64                 `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	MaskUrl       *string                `protobuf:"bytes,5,opt,name=maskUrl" json:"maskUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMask) Reset() {
	*x = VideoMask{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMask) ProtoMessage() {}

func (x *VideoMask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMask.ProtoReflect.Descriptor instead.
func (*VideoMask) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{1}
}

func (x *VideoMask) GetCid() int64 {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return 0
}

func (x *VideoMask) GetPlat() int32 {
	if x != nil && x.Plat != nil {
		return *x.Plat
	}
	return 0
}

func (x *VideoMask) GetFps() int32 {
	if x != nil && x.Fps != nil {
		return *x.Fps
	}
	return 0
}

func (x *VideoMask) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *VideoMask) GetMaskUrl() string {
	if x != nil && x.MaskUrl != nil {
		return *x.MaskUrl
	}
	return ""
}

type VideoSubtitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lan           *string                `protobuf:"bytes,1,opt,name=lan" json:"lan,omitempty"`
	LanDoc        *string                `protobuf:"bytes,2,opt,name=lanDoc" json:"lanDoc,omitempty"`
	Subtitles     []*SubtitleItem        `protobuf:"bytes,3,rep,name=subtitles" json:"subtitles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSubtitle) Reset() {
	*x = VideoSubtitle{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSubtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSubtitle) ProtoMessage() {}

func (x *VideoSubtitle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSubtitle.ProtoReflect.Descriptor instead.
func (*VideoSubtitle) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{2}
}

func (x *VideoSubtitle) GetLan() string {
	if x != nil && x.Lan != nil {
		return *x.Lan
	}
	return ""
}

func (x *VideoSubtitle) GetLanDoc() string {
	if x != nil && x.LanDoc != nil {
		return *x.LanDoc
	}
	return ""
}

func (x *VideoSubtitle) GetSubtitles() []*SubtitleItem {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

type DanmakuFlagConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecFlag       *int32                 `protobuf:"varint,1,opt,name=recFlag" json:"recFlag,omitempty"`
	RecText       *string                `protobuf:"bytes,2,opt,name=recText" json:"recText,omitempty"`
	RecSwitch     *int32                 `protobuf:"varint,3,opt,name=recSwitch" json:"recSwitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuFlagConfig) Reset() {
	*x = DanmakuFlagConfig{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuFlagConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuFlagConfig) ProtoMessage() {}

func (x *DanmakuFlagConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuFlagConfig.ProtoReflect.Descriptor instead.
func (*DanmakuFlagConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{3}
}

func (x *DanmakuFlagConfig) GetRecFlag() int32 {
	if x != nil && x.RecFlag != nil {
		return *x.RecFlag
	}
	return 0
}

func (x *DanmakuFlagConfig) GetRecText() string {
	if x != nil && x.RecText != nil {
		return *x.RecText
	}
	return ""
}

func (x *DanmakuFlagConfig) GetRecSwitch() int32 {
	if x != nil && x.RecSwitch != nil {
		return *x.RecSwitch
	}
	return 0
}

type DanmuPlayerViewConfig struct {
	state                      protoimpl.MessageState    `protogen:"open.v1"`
	DanmukuDefaultPlayerConfig *DanmuDefaultPlayerConfig `protobuf:"bytes,1,opt,name=danmukuDefaultPlayerConfig" json:"danmukuDefaultPlayerConfig,omitempty"`
	DanmukuPlayerConfig        *DanmuPlayerConfig        `protobuf:"bytes,2,opt,name=danmukuPlayerConfig" json:"danmukuPlayerConfig,omitempty"`
	DanmukuPlayerDynamicConfig *DanmuPlayerDynamicConfig `protobuf:"bytes,3,opt,name=danmukuPlayerDynamicConfig" json:"danmukuPlayerDynamicConfig,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DanmuPlayerViewConfig) Reset() {
	*x = DanmuPlayerViewConfig{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuPlayerViewConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuPlayerViewConfig) ProtoMessage() {}

func (x *DanmuPlayerViewConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuPlayerViewConfig.ProtoReflect.Descriptor instead.
func (*DanmuPlayerViewConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{4}
}

func (x *DanmuPlayerViewConfig) GetDanmukuDefaultPlayerConfig() *DanmuDefaultPlayerConfig {
	if x != nil {
		return x.DanmukuDefaultPlayerConfig
	}
	return nil
}

func (x *DanmuPlayerViewConfig) GetDanmukuPlayerConfig() *DanmuPlayerConfig {
	if x != nil {
		return x.DanmukuPlayerConfig
	}
	return nil
}

func (x *DanmuPlayerViewConfig) GetDanmukuPlayerDynamicConfig() *DanmuPlayerDynamicConfig {
	if x != nil {
		return x.DanmukuPlayerDynamicConfig
	}
	return nil
}

type SubtitleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *UserInfo              `protobuf:"bytes,6,opt,name=author" json:"author,omitempty"`
	IdStr         *string                `protobuf:"bytes,1,opt,name=idStr" json:"idStr,omitempty"`
	Id            *int64                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	LanDoc        *string                `protobuf:"bytes,4,opt,name=lanDoc" json:"lanDoc,omitempty"`
	Lan           *string                `protobuf:"bytes,3,opt,name=lan" json:"lan,omitempty"`
	SubtitleUrl   *string                `protobuf:"bytes,5,opt,name=subtitleUrl" json:"subtitleUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleItem) Reset() {
	*x = SubtitleItem{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleItem) ProtoMessage() {}

func (x *SubtitleItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleItem.ProtoReflect.Descriptor instead.
func (*SubtitleItem) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{5}
}

func (x *SubtitleItem) GetAuthor() *UserInfo {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *SubtitleItem) GetIdStr() string {
	if x != nil && x.IdStr != nil {
		return *x.IdStr
	}
	return ""
}

func (x *SubtitleItem) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SubtitleItem) GetLanDoc() string {
	if x != nil && x.LanDoc != nil {
		return *x.LanDoc
	}
	return ""
}

func (x *SubtitleItem) GetLan() string {
	if x != nil && x.Lan != nil {
		return *x.Lan
	}
	return ""
}

func (x *SubtitleItem) GetSubtitleUrl() string {
	if x != nil && x.SubtitleUrl != nil {
		return *x.SubtitleUrl
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Face          *string                `protobuf:"bytes,4,opt,name=face" json:"face,omitempty"`
	Mid           *int64                 `protobuf:"varint,1,opt,name=mid" json:"mid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Rank          *int32                 `protobuf:"varint,6,opt,name=rank" json:"rank,omitempty"`
	Sex           *string                `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Sign          *string                `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetFace() string {
	if x != nil && x.Face != nil {
		return *x.Face
	}
	return ""
}

func (x *UserInfo) GetMid() int64 {
	if x != nil && x.Mid != nil {
		return *x.Mid
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserInfo) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

func (x *UserInfo) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *UserInfo) GetSign() string {
	if x != nil && x.Sign != nil {
		return *x.Sign
	}
	return ""
}

type DanmuDefaultPlayerConfig struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	PlayerDanmakuUseDefaultConfig    *bool                  `protobuf:"varint,1,opt,name=playerDanmakuUseDefaultConfig" json:"playerDanmakuUseDefaultConfig,omitempty"`
	PlayerDanmakuAiRecommendedSwitch *bool                  `protobuf:"varint,4,opt,name=playerDanmakuAiRecommendedSwitch" json:"playerDanmakuAiRecommendedSwitch,omitempty"`
	PlayerDanmakuAiRecommendedLevel  *int32                 `protobuf:"varint,5,opt,name=playerDanmakuAiRecommendedLevel" json:"playerDanmakuAiRecommendedLevel,omitempty"`
	PlayerDanmakuBlocktop            *bool                  `protobuf:"varint,6,opt,name=playerDanmakuBlocktop" json:"playerDanmakuBlocktop,omitempty"`
	PlayerDanmakuBlockscroll         *bool                  `protobuf:"varint,7,opt,name=playerDanmakuBlockscroll" json:"playerDanmakuBlockscroll,omitempty"`
	PlayerDanmakuBlockbottom         *bool                  `protobuf:"varint,8,opt,name=playerDanmakuBlockbottom" json:"playerDanmakuBlockbottom,omitempty"`
	PlayerDanmakuBlockcolorful       *bool                  `protobuf:"varint,9,opt,name=playerDanmakuBlockcolorful" json:"playerDanmakuBlockcolorful,omitempty"`
	PlayerDanmakuBlockrepeat         *bool                  `protobuf:"varint,10,opt,name=playerDanmakuBlockrepeat" json:"playerDanmakuBlockrepeat,omitempty"`
	PlayerDanmakuBlockspecial        *bool                  `protobuf:"varint,11,opt,name=playerDanmakuBlockspecial" json:"playerDanmakuBlockspecial,omitempty"`
	PlayerDanmakuOpacity             *float32               `protobuf:"fixed32,12,opt,name=playerDanmakuOpacity" json:"playerDanmakuOpacity,omitempty"`
	PlayerDanmakuScalingfactor       *float32               `protobuf:"fixed32,13,opt,name=playerDanmakuScalingfactor" json:"playerDanmakuScalingfactor,omitempty"`
	PlayerDanmakuDomain              *float32               `protobuf:"fixed32,14,opt,name=playerDanmakuDomain" json:"playerDanmakuDomain,omitempty"`
	PlayerDanmakuSpeed               *int32                 `protobuf:"varint,15,opt,name=playerDanmakuSpeed" json:"playerDanmakuSpeed,omitempty"`
	InlinePlayerDanmakuSwitch        *bool                  `protobuf:"varint,16,opt,name=inlinePlayerDanmakuSwitch" json:"inlinePlayerDanmakuSwitch,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DanmuDefaultPlayerConfig) Reset() {
	*x = DanmuDefaultPlayerConfig{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuDefaultPlayerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuDefaultPlayerConfig) ProtoMessage() {}

func (x *DanmuDefaultPlayerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuDefaultPlayerConfig.ProtoReflect.Descriptor instead.
func (*DanmuDefaultPlayerConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{7}
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuUseDefaultConfig() bool {
	if x != nil && x.PlayerDanmakuUseDefaultConfig != nil {
		return *x.PlayerDanmakuUseDefaultConfig
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuAiRecommendedSwitch() bool {
	if x != nil && x.PlayerDanmakuAiRecommendedSwitch != nil {
		return *x.PlayerDanmakuAiRecommendedSwitch
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuAiRecommendedLevel() int32 {
	if x != nil && x.PlayerDanmakuAiRecommendedLevel != nil {
		return *x.PlayerDanmakuAiRecommendedLevel
	}
	return 0
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlocktop() bool {
	if x != nil && x.PlayerDanmakuBlocktop != nil {
		return *x.PlayerDanmakuBlocktop
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlockscroll() bool {
	if x != nil && x.PlayerDanmakuBlockscroll != nil {
		return *x.PlayerDanmakuBlockscroll
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlockbottom() bool {
	if x != nil && x.PlayerDanmakuBlockbottom != nil {
		return *x.PlayerDanmakuBlockbottom
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlockcolorful() bool {
	if x != nil && x.PlayerDanmakuBlockcolorful != nil {
		return *x.PlayerDanmakuBlockcolorful
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlockrepeat() bool {
	if x != nil && x.PlayerDanmakuBlockrepeat != nil {
		return *x.PlayerDanmakuBlockrepeat
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuBlockspecial() bool {
	if x != nil && x.PlayerDanmakuBlockspecial != nil {
		return *x.PlayerDanmakuBlockspecial
	}
	return false
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuOpacity() float32 {
	if x != nil && x.PlayerDanmakuOpacity != nil {
		return *x.PlayerDanmakuOpacity
	}
	return 0
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuScalingfactor() float32 {
	if x != nil && x.PlayerDanmakuScalingfactor != nil {
		return *x.PlayerDanmakuScalingfactor
	}
	return 0
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuDomain() float32 {
	if x != nil && x.PlayerDanmakuDomain != nil {
		return *x.PlayerDanmakuDomain
	}
	return 0
}

func (x *DanmuDefaultPlayerConfig) GetPlayerDanmakuSpeed() int32 {
	if x != nil && x.PlayerDanmakuSpeed != nil {
		return *x.PlayerDanmakuSpeed
	}
	return 0
}

func (x *DanmuDefaultPlayerConfig) GetInlinePlayerDanmakuSwitch() bool {
	if x != nil && x.InlinePlayerDanmakuSwitch != nil {
		return *x.InlinePlayerDanmakuSwitch
	}
	return false
}

type DanmuPlayerConfig struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	PlayerDanmakuSwitchSave          *bool                  `protobuf:"varint,1,opt,name=playerDanmakuSwitchSave" json:"playerDanmakuSwitchSave,omitempty"`
	PlayerDanmakuSwitch              *bool                  `protobuf:"varint,2,opt,name=playerDanmakuSwitch" json:"playerDanmakuSwitch,omitempty"`
	PlayerDanmakuUseDefaultConfig    *bool                  `protobuf:"varint,3,opt,name=playerDanmakuUseDefaultConfig" json:"playerDanmakuUseDefaultConfig,omitempty"`
	PlayerDanmakuAiRecommendedSwitch *bool                  `protobuf:"varint,4,opt,name=playerDanmakuAiRecommendedSwitch" json:"playerDanmakuAiRecommendedSwitch,omitempty"`
	PlayerDanmakuAiRecommendedLevel  *int32                 `protobuf:"varint,5,opt,name=playerDanmakuAiRecommendedLevel" json:"playerDanmakuAiRecommendedLevel,omitempty"`
	PlayerDanmakuBlocktop            *bool                  `protobuf:"varint,6,opt,name=playerDanmakuBlocktop" json:"playerDanmakuBlocktop,omitempty"`
	PlayerDanmakuBlockscroll         *bool                  `protobuf:"varint,7,opt,name=playerDanmakuBlockscroll" json:"playerDanmakuBlockscroll,omitempty"`
	PlayerDanmakuBlockbottom         *bool                  `protobuf:"varint,8,opt,name=playerDanmakuBlockbottom" json:"playerDanmakuBlockbottom,omitempty"`
	PlayerDanmakuBlockcolorful       *bool                  `protobuf:"varint,9,opt,name=playerDanmakuBlockcolorful" json:"playerDanmakuBlockcolorful,omitempty"`
	PlayerDanmakuBlockrepeat         *bool                  `protobuf:"varint,10,opt,name=playerDanmakuBlockrepeat" json:"playerDanmakuBlockrepeat,omitempty"`
	PlayerDanmakuBlockspecial        *bool                  `protobuf:"varint,11,opt,name=playerDanmakuBlockspecial" json:"playerDanmakuBlockspecial,omitempty"`
	PlayerDanmakuOpacity             *float32               `protobuf:"fixed32,12,opt,name=playerDanmakuOpacity" json:"playerDanmakuOpacity,omitempty"`
	PlayerDanmakuScalingfactor       *float32               `protobuf:"fixed32,13,opt,name=playerDanmakuScalingfactor" json:"playerDanmakuScalingfactor,omitempty"`
	PlayerDanmakuDomain              *float32               `protobuf:"fixed32,14,opt,name=playerDanmakuDomain" json:"playerDanmakuDomain,omitempty"`
	PlayerDanmakuSpeed               *int32                 `protobuf:"varint,15,opt,name=playerDanmakuSpeed" json:"playerDanmakuSpeed,omitempty"`
	PlayerDanmakuEnableblocklist     *bool                  `protobuf:"varint,16,opt,name=playerDanmakuEnableblocklist" json:"playerDanmakuEnableblocklist,omitempty"`
	InlinePlayerDanmakuSwitch        *bool                  `protobuf:"varint,17,opt,name=inlinePlayerDanmakuSwitch" json:"inlinePlayerDanmakuSwitch,omitempty"`
	InlinePlayerDanmakuConfig        *int32                 `protobuf:"varint,18,opt,name=inlinePlayerDanmakuConfig" json:"inlinePlayerDanmakuConfig,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DanmuPlayerConfig) Reset() {
	*x = DanmuPlayerConfig{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuPlayerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuPlayerConfig) ProtoMessage() {}

func (x *DanmuPlayerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuPlayerConfig.ProtoReflect.Descriptor instead.
func (*DanmuPlayerConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{8}
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuSwitchSave() bool {
	if x != nil && x.PlayerDanmakuSwitchSave != nil {
		return *x.PlayerDanmakuSwitchSave
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuSwitch() bool {
	if x != nil && x.PlayerDanmakuSwitch != nil {
		return *x.PlayerDanmakuSwitch
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuUseDefaultConfig() bool {
	if x != nil && x.PlayerDanmakuUseDefaultConfig != nil {
		return *x.PlayerDanmakuUseDefaultConfig
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuAiRecommendedSwitch() bool {
	if x != nil && x.PlayerDanmakuAiRecommendedSwitch != nil {
		return *x.PlayerDanmakuAiRecommendedSwitch
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuAiRecommendedLevel() int32 {
	if x != nil && x.PlayerDanmakuAiRecommendedLevel != nil {
		return *x.PlayerDanmakuAiRecommendedLevel
	}
	return 0
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlocktop() bool {
	if x != nil && x.PlayerDanmakuBlocktop != nil {
		return *x.PlayerDanmakuBlocktop
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlockscroll() bool {
	if x != nil && x.PlayerDanmakuBlockscroll != nil {
		return *x.PlayerDanmakuBlockscroll
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlockbottom() bool {
	if x != nil && x.PlayerDanmakuBlockbottom != nil {
		return *x.PlayerDanmakuBlockbottom
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlockcolorful() bool {
	if x != nil && x.PlayerDanmakuBlockcolorful != nil {
		return *x.PlayerDanmakuBlockcolorful
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlockrepeat() bool {
	if x != nil && x.PlayerDanmakuBlockrepeat != nil {
		return *x.PlayerDanmakuBlockrepeat
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuBlockspecial() bool {
	if x != nil && x.PlayerDanmakuBlockspecial != nil {
		return *x.PlayerDanmakuBlockspecial
	}
	return false
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuOpacity() float32 {
	if x != nil && x.PlayerDanmakuOpacity != nil {
		return *x.PlayerDanmakuOpacity
	}
	return 0
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuScalingfactor() float32 {
	if x != nil && x.PlayerDanmakuScalingfactor != nil {
		return *x.PlayerDanmakuScalingfactor
	}
	return 0
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuDomain() float32 {
	if x != nil && x.PlayerDanmakuDomain != nil {
		return *x.PlayerDanmakuDomain
	}
	return 0
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuSpeed() int32 {
	if x != nil && x.PlayerDanmakuSpeed != nil {
		return *x.PlayerDanmakuSpeed
	}
	return 0
}

func (x *DanmuPlayerConfig) GetPlayerDanmakuEnableblocklist() bool {
	if x != nil && x.PlayerDanmakuEnableblocklist != nil {
		return *x.PlayerDanmakuEnableblocklist
	}
	return false
}

func (x *DanmuPlayerConfig) GetInlinePlayerDanmakuSwitch() bool {
	if x != nil && x.InlinePlayerDanmakuSwitch != nil {
		return *x.InlinePlayerDanmakuSwitch
	}
	return false
}

func (x *DanmuPlayerConfig) GetInlinePlayerDanmakuConfig() int32 {
	if x != nil && x.InlinePlayerDanmakuConfig != nil {
		return *x.InlinePlayerDanmakuConfig
	}
	return 0
}

type DanmuPlayerDynamicConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Progress            *int32                 `protobuf:"varint,1,opt,name=progress" json:"progress,omitempty"`
	PlayerDanmakuDomain *float32               `protobuf:"fixed32,14,opt,name=playerDanmakuDomain" json:"playerDanmakuDomain,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DanmuPlayerDynamicConfig) Reset() {
	*x = DanmuPlayerDynamicConfig{}
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuPlayerDynamicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuPlayerDynamicConfig) ProtoMessage() {}

func (x *DanmuPlayerDynamicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_dmviewreply_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuPlayerDynamicConfig.ProtoReflect.Descriptor instead.
func (*DanmuPlayerDynamicConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_response_dmviewreply_proto_rawDescGZIP(), []int{9}
}

func (x *DanmuPlayerDynamicConfig) GetProgress() int32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *DanmuPlayerDynamicConfig) GetPlayerDanmakuDomain() float32 {
	if x != nil && x.PlayerDanmakuDomain != nil {
		return *x.PlayerDanmakuDomain
	}
	return 0
}

var File_proto_app_response_dmviewreply_proto protoreflect.FileDescriptor

const file_proto_app_response_dmviewreply_proto_rawDesc = "" +
	"\n" +
	"$proto/app/response/dmviewreply.proto\x12\x06bbdown\"\xbf\x03\n" +
	"\vDmViewReply\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\x12%\n" +
	"\x04mask\x18\x02 \x01(\v2\x11.bbdown.VideoMaskR\x04mask\x121\n" +
	"\bsubtitle\x18\x03 \x01(\v2\x15.bbdown.VideoSubtitleR\bsubtitle\x12\x1e\n" +
	"\n" +
	"specialDms\x18\x04 \x03(\tR\n" +
	"specialDms\x121\n" +
	"\x06aiFlag\x18\x05 \x01(\v2\x19.bbdown.DanmakuFlagConfigR\x06aiFlag\x12A\n" +
	"\fplayerConfig\x18\x06 \x01(\v2\x1d.bbdown.DanmuPlayerViewConfigR\fplayerConfig\x12\"\n" +
	"\fsendBoxStyle\x18\a \x01(\x05R\fsendBoxStyle\x12\x14\n" +
	"\x05allow\x18\b \x01(\bR\x05allow\x12(\n" +
	"\x0fcheckBoxShowMsg\x18\t \x01(\tR\x0fcheckBoxShowMsg\x12\x1a\n" +
	"\bcheckBox\x18\n" +
	" \x01(\bR\bcheckBox\x12(\n" +
	"\x0ftextPlaceholder\x18\v \x01(\tR\x0ftextPlaceholder\"q\n" +
	"\tVideoMask\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x03R\x03cid\x12\x12\n" +
	"\x04plat\x18\x02 \x01(\x05R\x04plat\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\x05R\x03fps\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12\x18\n" +
	"\amaskUrl\x18\x05 \x01(\tR\amaskUrl\"m\n" +
	"\rVideoSubtitle\x12\x10\n" +
	"\x03lan\x18\x01 \x01(\tR\x03lan\x12\x16\n" +
	"\x06lanDoc\x18\x02 \x01(\tR\x06lanDoc\x122\n" +
	"\tsubtitles\x18\x03 \x03(\v2\x14.bbdown.SubtitleItemR\tsubtitles\"e\n" +
	"\x11DanmakuFlagConfig\x12\x18\n" +
	"\arecFlag\x18\x01 \x01(\x05R\arecFlag\x12\x18\n" +
	"\arecText\x18\x02 \x01(\tR\arecText\x12\x1c\n" +
	"\trecSwitch\x18\x03 \x01(\x05R\trecSwitch\"\xa8\x02\n" +
	"\x15DanmuPlayerViewConfig\x12`\n" +
	"\x1adanmukuDefaultPlayerConfig\x18\x01 \x01(\v2 .bbdown.DanmuDefaultPlayerConfigR\x1adanmukuDefaultPlayerConfig\x12K\n" +
	"\x13danmukuPlayerConfig\x18\x02 \x01(\v2\x19.bbdown.DanmuPlayerConfigR\x13danmukuPlayerConfig\x12`\n" +
	"\x1adanmukuPlayerDynamicConfig\x18\x03 \x01(\v2 .bbdown.DanmuPlayerDynamicConfigR\x1adanmukuPlayerDynamicConfig\"\xaa\x01\n" +
	"\fSubtitleItem\x12(\n" +
	"\x06author\x18\x06 \x01(\v2\x10.bbdown.UserInfoR\x06author\x12\x14\n" +
	"\x05idStr\x18\x01 \x01(\tR\x05idStr\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x16\n" +
	"\x06lanDoc\x18\x04 \x01(\tR\x06lanDoc\x12\x10\n" +
	"\x03lan\x18\x03 \x01(\tR\x03lan\x12 \n" +
	"\vsubtitleUrl\x18\x05 \x01(\tR\vsubtitleUrl\"~\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04face\x18\x04 \x01(\tR\x04face\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\x12\x12\n" +
	"\x04sign\x18\x05 \x01(\tR\x04sign\"\xf2\x06\n" +
	"\x18DanmuDefaultPlayerConfig\x12D\n" +
	"\x1dplayerDanmakuUseDefaultConfig\x18\x01 \x01(\bR\x1dplayerDanmakuUseDefaultConfig\x12J\n" +
	" playerDanmakuAiRecommendedSwitch\x18\x04 \x01(\bR playerDanmakuAiRecommendedSwitch\x12H\n" +
	"\x1fplayerDanmakuAiRecommendedLevel\x18\x05 \x01(\x05R\x1fplayerDanmakuAiRecommendedLevel\x124\n" +
	"\x15playerDanmakuBlocktop\x18\x06 \x01(\bR\x15playerDanmakuBlocktop\x12:\n" +
	"\x18playerDanmakuBlockscroll\x18\a \x01(\bR\x18playerDanmakuBlockscroll\x12:\n" +
	"\x18playerDanmakuBlockbottom\x18\b \x01(\bR\x18playerDanmakuBlockbottom\x12>\n" +
	"\x1aplayerDanmakuBlockcolorful\x18\t \x01(\bR\x1aplayerDanmakuBlockcolorful\x12:\n" +
	"\x18playerDanmakuBlockrepeat\x18\n" +
	" \x01(\bR\x18playerDanmakuBlockrepeat\x12<\n" +
	"\x19playerDanmakuBlockspecial\x18\v \x01(\bR\x19playerDanmakuBlockspecial\x122\n" +
	"\x14playerDanmakuOpacity\x18\f \x01(\x02R\x14playerDanmakuOpacity\x12>\n" +
	"\x1aplayerDanmakuScalingfactor\x18\r \x01(\x02R\x1aplayerDanmakuScalingfactor\x120\n" +
	"\x13playerDanmakuDomain\x18\x0e \x01(\x02R\x13playerDanmakuDomain\x12.\n" +
	"\x12playerDanmakuSpeed\x18\x0f \x01(\x05R\x12playerDanmakuSpeed\x12<\n" +
	"\x19inlinePlayerDanmakuSwitch\x18\x10 \x01(\bR\x19inlinePlayerDanmakuSwitch\"\xd9\b\n" +
	"\x11DanmuPlayerConfig\x128\n" +
	"\x17playerDanmakuSwitchSave\x18\x01 \x01(\bR\x17playerDanmakuSwitchSave\x120\n" +
	"\x13playerDanmakuSwitch\x18\x02 \x01(\bR\x13playerDanmakuSwitch\x12D\n" +
	"\x1dplayerDanmakuUseDefaultConfig\x18\x03 \x01(\bR\x1dplayerDanmakuUseDefaultConfig\x12J\n" +
	" playerDanmakuAiRecommendedSwitch\x18\x04 \x01(\bR playerDanmakuAiRecommendedSwitch\x12H\n" +
	"\x1fplayerDanmakuAiRecommendedLevel\x18\x05 \x01(\x05R\x1fplayerDanmakuAiRecommendedLevel\x124\n" +
	"\x15playerDanmakuBlocktop\x18\x06 \x01(\bR\x15playerDanmakuBlocktop\x12:\n" +
	"\x18playerDanmakuBlockscroll\x18\a \x01(\bR\x18playerDanmakuBlockscroll\x12:\n" +
	"\x18playerDanmakuBlockbottom\x18\b \x01(\bR\x18playerDanmakuBlockbottom\x12>\n" +
	"\x1aplayerDanmakuBlockcolorful\x18\t \x01(\bR\x1aplayerDanmakuBlockcolorful\x12:\n" +
	"\x18playerDanmakuBlockrepeat\x18\n" +
	" \x01(\bR\x18playerDanmakuBlockrepeat\x12<\n" +
	"\x19playerDanmakuBlockspecial\x18\v \x01(\bR\x19playerDanmakuBlockspecial\x122\n" +
	"\x14playerDanmakuOpacity\x18\f \x01(\x02R\x14playerDanmakuOpacity\x12>\n" +
	"\x1aplayerDanmakuScalingfactor\x18\r \x01(\x02R\x1aplayerDanmakuScalingfactor\x120\n" +
	"\x13playerDanmakuDomain\x18\x0e \x01(\x02R\x13playerDanmakuDomain\x12.\n" +
	"\x12playerDanmakuSpeed\x18\x0f \x01(\x05R\x12playerDanmakuSpeed\x12B\n" +
	"\x1cplayerDanmakuEnableblocklist\x18\x10 \x01(\bR\x1cplayerDanmakuEnableblocklist\x12<\n" +
	"\x19inlinePlayerDanmakuSwitch\x18\x11 \x01(\bR\x19inlinePlayerDanmakuSwitch\x12<\n" +
	"\x19inlinePlayerDanmakuConfig\x18\x12 \x01(\x05R\x19inlinePlayerDanmakuConfig\"h\n" +
	"\x18DanmuPlayerDynamicConfig\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x120\n" +
	"\x13playerDanmakuDomain\x18\x0e \x01(\x02R\x13playerDanmakuDomainB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_response_dmviewreply_proto_rawDescOnce sync.Once
	file_proto_app_response_dmviewreply_proto_rawDescData []byte
)

func file_proto_app_response_dmviewreply_proto_rawDescGZIP() []byte {
	file_proto_app_response_dmviewreply_proto_rawDescOnce.Do(func() {
		file_proto_app_response_dmviewreply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_response_dmviewreply_proto_rawDesc), len(file_proto_app_response_dmviewreply_proto_rawDesc)))
	})
	return file_proto_app_response_dmviewreply_proto_rawDescData
}

var file_proto_app_response_dmviewreply_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_app_response_dmviewreply_proto_goTypes = []any{
	(*DmViewReply)(nil),              // 0: bbdown.DmViewReply
	(*VideoMask)(nil),                // 1: bbdown.VideoMask
	(*VideoSubtitle)(nil),            // 2: bbdown.VideoSubtitle
	(*DanmakuFlagConfig)(nil),        // 3: bbdown.DanmakuFlagConfig
	(*DanmuPlayerViewConfig)(nil),    // 4: bbdown.DanmuPlayerViewConfig
	(*SubtitleItem)(nil),             // 5: bbdown.SubtitleItem
	(*UserInfo)(nil),                 // 6: bbdown.UserInfo
	(*DanmuDefaultPlayerConfig)(nil), // 7: bbdown.DanmuDefaultPlayerConfig
	(*DanmuPlayerConfig)(nil),        // 8: bbdown.DanmuPlayerConfig
	(*DanmuPlayerDynamicConfig)(nil), // 9: bbdown.DanmuPlayerDynamicConfig
}
var file_proto_app_response_dmviewreply_proto_depIdxs = []int32{
	1, // 0: bbdown.DmViewReply.mask:type_name -> bbdown.VideoMask
	2, // 1: bbdown.DmViewReply.subtitle:type_name -> bbdown.VideoSubtitle
	3, // 2: bbdown.DmViewReply.aiFlag:type_name -> bbdown.DanmakuFlagConfig
	4, // 3: bbdown.DmViewReply.playerConfig:type_name -> bbdown.DanmuPlayerViewConfig
	5, // 4: bbdown.VideoSubtitle.subtitles:type_name -> bbdown.SubtitleItem
	7, // 5: bbdown.DanmuPlayerViewConfig.danmukuDefaultPlayerConfig:type_name -> bbdown.DanmuDefaultPlayerConfig
	8, // 6: bbdown.DanmuPlayerViewConfig.danmukuPlayerConfig:type_name -> bbdown.DanmuPlayerConfig
	9, // 7: bbdown.DanmuPlayerViewConfig.danmukuPlayerDynamicConfig:type_name -> bbdown.DanmuPlayerDynamicConfig
	6, // 8: bbdown.SubtitleItem.author:type_name -> bbdown.UserInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_app_response_dmviewreply_proto_init() }
func file_proto_app_response_dmviewreply_proto_init() {
	if File_proto_app_response_dmviewreply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_response_dmviewreply_proto_rawDesc), len(file_proto_app_response_dmviewreply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_response_dmviewreply_proto_goTypes,
		DependencyIndexes: file_proto_app_response_dmviewreply_proto_depIdxs,
		MessageInfos:      file_proto_app_response_dmviewreply_proto_msgTypes,
	}.Build()
	File_proto_app_response_dmviewreply_proto = out.File
	file_proto_app_response_dmviewreply_proto_goTypes = nil
	file_proto_app_response_dmviewreply_proto_depIdxs = nil
}
