// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/payload/dmviewreq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmViewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *int64                 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Oid           *int64                 `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	Type          *int32                 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Spmid         *string                `protobuf:"bytes,4,opt,name=spmid" json:"spmid,omitempty"`
	IsHardBoot    *int32                 `protobuf:"varint,5,opt,name=isHardBoot" json:"isHardBoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmViewReq) Reset() {
	*x = DmViewReq{}
	mi := &file_proto_app_payload_dmviewreq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmViewReq) ProtoMessage() {}

func (x *DmViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_payload_dmviewreq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmViewReq.ProtoReflect.Descriptor instead.
func (*DmViewReq) Descriptor() ([]byte, []int) {
	return file_proto_app_payload_dmviewreq_proto_rawDescGZIP(), []int{0}
}

func (x *DmViewReq) GetPid() int64 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *DmViewReq) GetOid() int64 {
	if x != nil && x.Oid != nil {
		return *x.Oid
	}
	return 0
}

func (x *DmViewReq) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *DmViewReq) GetSpmid() string {
	if x != nil && x.Spmid != nil {
		return *x.Spmid
	}
	return ""
}

func (x *DmViewReq) GetIsHardBoot() int32 {
	if x != nil && x.IsHardBoot != nil {
		return *x.IsHardBoot
	}
	return 0
}

var File_proto_app_payload_dmviewreq_proto protoreflect.FileDescriptor

const file_proto_app_payload_dmviewreq_proto_rawDesc = "" +
	"\n" +
	"!proto/app/payload/dmviewreq.proto\x12\x06bbdown\"y\n" +
	"\tDmViewReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05spmid\x18\x04 \x01(\tR\x05spmid\x12\x1e\n" +
	"\n" +
	"isHardBoot\x18\x05 \x01(\x05R\n" +
	"isHardBootB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_payload_dmviewreq_proto_rawDescOnce sync.Once
	file_proto_app_payload_dmviewreq_proto_rawDescData []byte
)

func file_proto_app_payload_dmviewreq_proto_rawDescGZIP() []byte {
	file_proto_app_payload_dmviewreq_proto_rawDescOnce.Do(func() {
		file_proto_app_payload_dmviewreq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_payload_dmviewreq_proto_rawDesc), len(file_proto_app_payload_dmviewreq_proto_rawDesc)))
	})
	return file_proto_app_payload_dmviewreq_proto_rawDescData
}

var file_proto_app_payload_dmviewreq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_payload_dmviewreq_proto_goTypes = []any{
	(*DmViewReq)(nil), // 0: bbdown.DmViewReq
}
var file_proto_app_payload_dmviewreq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_payload_dmviewreq_proto_init() }
func file_proto_app_payload_dmviewreq_proto_init() {
	if File_proto_app_payload_dmviewreq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_payload_dmviewreq_proto_rawDesc), len(file_proto_app_payload_dmviewreq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_payload_dmviewreq_proto_goTypes,
		DependencyIndexes: file_proto_app_payload_dmviewreq_proto_depIdxs,
		MessageInfos:      file_proto_app_payload_dmviewreq_proto_msgTypes,
	}.Build()
	File_proto_app_payload_dmviewreq_proto = out.File
	file_proto_app_payload_dmviewreq_proto_goTypes = nil
	file_proto_app_payload_dmviewreq_proto_depIdxs = nil
}
