// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/header/fawkesreq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FawkesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appkey        *string                `protobuf:"bytes,1,opt,name=appkey" json:"appkey,omitempty"`
	Env           *string                `protobuf:"bytes,2,opt,name=env" json:"env,omitempty"`
	SessionId     *string                `protobuf:"bytes,3,opt,name=sessionId" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FawkesReq) Reset() {
	*x = FawkesReq{}
	mi := &file_proto_app_header_fawkesreq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FawkesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FawkesReq) ProtoMessage() {}

func (x *FawkesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_header_fawkesreq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FawkesReq.ProtoReflect.Descriptor instead.
func (*FawkesReq) Descriptor() ([]byte, []int) {
	return file_proto_app_header_fawkesreq_proto_rawDescGZIP(), []int{0}
}

func (x *FawkesReq) GetAppkey() string {
	if x != nil && x.Appkey != nil {
		return *x.Appkey
	}
	return ""
}

func (x *FawkesReq) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *FawkesReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

var File_proto_app_header_fawkesreq_proto protoreflect.FileDescriptor

const file_proto_app_header_fawkesreq_proto_rawDesc = "" +
	"\n" +
	" proto/app/header/fawkesreq.proto\x12\x06bbdown\"S\n" +
	"\tFawkesReq\x12\x16\n" +
	"\x06appkey\x18\x01 \x01(\tR\x06appkey\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1c\n" +
	"\tsessionId\x18\x03 \x01(\tR\tsessionIdB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_header_fawkesreq_proto_rawDescOnce sync.Once
	file_proto_app_header_fawkesreq_proto_rawDescData []byte
)

func file_proto_app_header_fawkesreq_proto_rawDescGZIP() []byte {
	file_proto_app_header_fawkesreq_proto_rawDescOnce.Do(func() {
		file_proto_app_header_fawkesreq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_header_fawkesreq_proto_rawDesc), len(file_proto_app_header_fawkesreq_proto_rawDesc)))
	})
	return file_proto_app_header_fawkesreq_proto_rawDescData
}

var file_proto_app_header_fawkesreq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_header_fawkesreq_proto_goTypes = []any{
	(*FawkesReq)(nil), // 0: bbdown.FawkesReq
}
var file_proto_app_header_fawkesreq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_header_fawkesreq_proto_init() }
func file_proto_app_header_fawkesreq_proto_init() {
	if File_proto_app_header_fawkesreq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_header_fawkesreq_proto_rawDesc), len(file_proto_app_header_fawkesreq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_header_fawkesreq_proto_goTypes,
		DependencyIndexes: file_proto_app_header_fawkesreq_proto_depIdxs,
		MessageInfos:      file_proto_app_header_fawkesreq_proto_msgTypes,
	}.Build()
	File_proto_app_header_fawkesreq_proto = out.File
	file_proto_app_header_fawkesreq_proto_goTypes = nil
	file_proto_app_header_fawkesreq_proto_depIdxs = nil
}
