// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/header/metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     *string                `protobuf:"bytes,1,opt,name=accessKey" json:"accessKey,omitempty"`
	MobiApp       *string                `protobuf:"bytes,2,opt,name=mobiApp" json:"mobiApp,omitempty"`
	Device        *string                `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	Build         *int32                 `protobuf:"varint,4,opt,name=build" json:"build,omitempty"`
	Channel       *string                `protobuf:"bytes,5,opt,name=channel" json:"channel,omitempty"`
	Buvid         *string                `protobuf:"bytes,6,opt,name=buvid" json:"buvid,omitempty"`
	Platform      *string                `protobuf:"bytes,7,opt,name=platform" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_app_header_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_header_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_app_header_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetAccessKey() string {
	if x != nil && x.AccessKey != nil {
		return *x.AccessKey
	}
	return ""
}

func (x *Metadata) GetMobiApp() string {
	if x != nil && x.MobiApp != nil {
		return *x.MobiApp
	}
	return ""
}

func (x *Metadata) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *Metadata) GetBuild() int32 {
	if x != nil && x.Build != nil {
		return *x.Build
	}
	return 0
}

func (x *Metadata) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *Metadata) GetBuvid() string {
	if x != nil && x.Buvid != nil {
		return *x.Buvid
	}
	return ""
}

func (x *Metadata) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

var File_proto_app_header_metadata_proto protoreflect.FileDescriptor

const file_proto_app_header_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/app/header/metadata.proto\x12\x06bbdown\"\xbc\x01\n" +
	"\bMetadata\x12\x1c\n" +
	"\taccessKey\x18\x01 \x01(\tR\taccessKey\x12\x18\n" +
	"\amobiApp\x18\x02 \x01(\tR\amobiApp\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x14\n" +
	"\x05build\x18\x04 \x01(\x05R\x05build\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x14\n" +
	"\x05buvid\x18\x06 \x01(\tR\x05buvid\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatformB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_header_metadata_proto_rawDescOnce sync.Once
	file_proto_app_header_metadata_proto_rawDescData []byte
)

func file_proto_app_header_metadata_proto_rawDescGZIP() []byte {
	file_proto_app_header_metadata_proto_rawDescOnce.Do(func() {
		file_proto_app_header_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_header_metadata_proto_rawDesc), len(file_proto_app_header_metadata_proto_rawDesc)))
	})
	return file_proto_app_header_metadata_proto_rawDescData
}

var file_proto_app_header_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_header_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: bbdown.Metadata
}
var file_proto_app_header_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_header_metadata_proto_init() }
func file_proto_app_header_metadata_proto_init() {
	if File_proto_app_header_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_header_metadata_proto_rawDesc), len(file_proto_app_header_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_header_metadata_proto_goTypes,
		DependencyIndexes: file_proto_app_header_metadata_proto_depIdxs,
		MessageInfos:      file_proto_app_header_metadata_proto_msgTypes,
	}.Build()
	File_proto_app_header_metadata_proto = out.File
	file_proto_app_header_metadata_proto_goTypes = nil
	file_proto_app_header_metadata_proto_depIdxs = nil
}
