// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/header/network.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network_TYPE int32

const (
	Network_NT_UNKNOWN Network_TYPE = 0
	Network_WIFI       Network_TYPE = 1
	Network_CELLULAR   Network_TYPE = 2
	Network_OFFLINE    Network_TYPE = 3
	Network_OTHERNET   Network_TYPE = 4
	Network_ETHERNET   Network_TYPE = 5
)

// Enum value maps for Network_TYPE.
var (
	Network_TYPE_name = map[int32]string{
		0: "NT_UNKNOWN",
		1: "WIFI",
		2: "CELLULAR",
		3: "OFFLINE",
		4: "OTHERNET",
		5: "ETHERNET",
	}
	Network_TYPE_value = map[string]int32{
		"NT_UNKNOWN": 0,
		"WIFI":       1,
		"CELLULAR":   2,
		"OFFLINE":    3,
		"OTHERNET":   4,
		"ETHERNET":   5,
	}
)

func (x Network_TYPE) Enum() *Network_TYPE {
	p := new(Network_TYPE)
	*p = x
	return p
}

func (x Network_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_app_header_network_proto_enumTypes[0].Descriptor()
}

func (Network_TYPE) Type() protoreflect.EnumType {
	return &file_proto_app_header_network_proto_enumTypes[0]
}

func (x Network_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Network_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Network_TYPE(num)
	return nil
}

// Deprecated: Use Network_TYPE.Descriptor instead.
func (Network_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proto_app_header_network_proto_rawDescGZIP(), []int{0, 0}
}

type Network_TF int32

const (
	Network_TF_UNKNOWN Network_TF = 0
	Network_U_CARD     Network_TF = 1
	Network_U_PKG      Network_TF = 2
	Network_C_CARD     Network_TF = 3
	Network_C_PKG      Network_TF = 4
	Network_T_CARD     Network_TF = 5
	Network_T_PKG      Network_TF = 6
)

// Enum value maps for Network_TF.
var (
	Network_TF_name = map[int32]string{
		0: "TF_UNKNOWN",
		1: "U_CARD",
		2: "U_PKG",
		3: "C_CARD",
		4: "C_PKG",
		5: "T_CARD",
		6: "T_PKG",
	}
	Network_TF_value = map[string]int32{
		"TF_UNKNOWN": 0,
		"U_CARD":     1,
		"U_PKG":      2,
		"C_CARD":     3,
		"C_PKG":      4,
		"T_CARD":     5,
		"T_PKG":      6,
	}
)

func (x Network_TF) Enum() *Network_TF {
	p := new(Network_TF)
	*p = x
	return p
}

func (x Network_TF) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network_TF) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_app_header_network_proto_enumTypes[1].Descriptor()
}

func (Network_TF) Type() protoreflect.EnumType {
	return &file_proto_app_header_network_proto_enumTypes[1]
}

func (x Network_TF) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Network_TF) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Network_TF(num)
	return nil
}

// Deprecated: Use Network_TF.Descriptor instead.
func (Network_TF) EnumDescriptor() ([]byte, []int) {
	return file_proto_app_header_network_proto_rawDescGZIP(), []int{0, 1}
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Network_TYPE          `protobuf:"varint,1,opt,name=type,enum=bbdown.Network_TYPE" json:"type,omitempty"`
	Tf            *Network_TF            `protobuf:"varint,2,opt,name=tf,enum=bbdown.Network_TF" json:"tf,omitempty"`
	Oid           *string                `protobuf:"bytes,3,opt,name=oid" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_proto_app_header_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_header_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_proto_app_header_network_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetType() Network_TYPE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Network_NT_UNKNOWN
}

func (x *Network) GetTf() Network_TF {
	if x != nil && x.Tf != nil {
		return *x.Tf
	}
	return Network_TF_UNKNOWN
}

func (x *Network) GetOid() string {
	if x != nil && x.Oid != nil {
		return *x.Oid
	}
	return ""
}

var File_proto_app_header_network_proto protoreflect.FileDescriptor

const file_proto_app_header_network_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/app/header/network.proto\x12\x06bbdown\"\x9d\x02\n" +
	"\aNetwork\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.bbdown.Network.TYPER\x04type\x12\"\n" +
	"\x02tf\x18\x02 \x01(\x0e2\x12.bbdown.Network.TFR\x02tf\x12\x10\n" +
	"\x03oid\x18\x03 \x01(\tR\x03oid\"W\n" +
	"\x04TYPE\x12\x0e\n" +
	"\n" +
	"NT_UNKNOWN\x10\x00\x12\b\n" +
	"\x04WIFI\x10\x01\x12\f\n" +
	"\bCELLULAR\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x03\x12\f\n" +
	"\bOTHERNET\x10\x04\x12\f\n" +
	"\bETHERNET\x10\x05\"Y\n" +
	"\x02TF\x12\x0e\n" +
	"\n" +
	"TF_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06U_CARD\x10\x01\x12\t\n" +
	"\x05U_PKG\x10\x02\x12\n" +
	"\n" +
	"\x06C_CARD\x10\x03\x12\t\n" +
	"\x05C_PKG\x10\x04\x12\n" +
	"\n" +
	"\x06T_CARD\x10\x05\x12\t\n" +
	"\x05T_PKG\x10\x06B\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_header_network_proto_rawDescOnce sync.Once
	file_proto_app_header_network_proto_rawDescData []byte
)

func file_proto_app_header_network_proto_rawDescGZIP() []byte {
	file_proto_app_header_network_proto_rawDescOnce.Do(func() {
		file_proto_app_header_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_header_network_proto_rawDesc), len(file_proto_app_header_network_proto_rawDesc)))
	})
	return file_proto_app_header_network_proto_rawDescData
}

var file_proto_app_header_network_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_app_header_network_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_header_network_proto_goTypes = []any{
	(Network_TYPE)(0), // 0: bbdown.Network.TYPE
	(Network_TF)(0),   // 1: bbdown.Network.TF
	(*Network)(nil),   // 2: bbdown.Network
}
var file_proto_app_header_network_proto_depIdxs = []int32{
	0, // 0: bbdown.Network.type:type_name -> bbdown.Network.TYPE
	1, // 1: bbdown.Network.tf:type_name -> bbdown.Network.TF
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_app_header_network_proto_init() }
func file_proto_app_header_network_proto_init() {
	if File_proto_app_header_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_header_network_proto_rawDesc), len(file_proto_app_header_network_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_header_network_proto_goTypes,
		DependencyIndexes: file_proto_app_header_network_proto_depIdxs,
		EnumInfos:         file_proto_app_header_network_proto_enumTypes,
		MessageInfos:      file_proto_app_header_network_proto_msgTypes,
	}.Build()
	File_proto_app_header_network_proto = out.File
	file_proto_app_header_network_proto_goTypes = nil
	file_proto_app_header_network_proto_depIdxs = nil
}
