// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/payload/playviewreq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayViewReq_CodeType int32

const (
	PlayViewReq_NOCODE  PlayViewReq_CodeType = 0
	PlayViewReq_CODE264 PlayViewReq_CodeType = 1
	PlayViewReq_CODE265 PlayViewReq_CodeType = 2
	PlayViewReq_CODEAV1 PlayViewReq_CodeType = 3
)

// Enum value maps for PlayViewReq_CodeType.
var (
	PlayViewReq_CodeType_name = map[int32]string{
		0: "NOCODE",
		1: "CODE264",
		2: "CODE265",
		3: "CODEAV1",
	}
	PlayViewReq_CodeType_value = map[string]int32{
		"NOCODE":  0,
		"CODE264": 1,
		"CODE265": 2,
		"CODEAV1": 3,
	}
)

func (x PlayViewReq_CodeType) Enum() *PlayViewReq_CodeType {
	p := new(PlayViewReq_CodeType)
	*p = x
	return p
}

func (x PlayViewReq_CodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayViewReq_CodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_app_payload_playviewreq_proto_enumTypes[0].Descriptor()
}

func (PlayViewReq_CodeType) Type() protoreflect.EnumType {
	return &file_proto_app_payload_playviewreq_proto_enumTypes[0]
}

func (x PlayViewReq_CodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PlayViewReq_CodeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PlayViewReq_CodeType(num)
	return nil
}

// Deprecated: Use PlayViewReq_CodeType.Descriptor instead.
func (PlayViewReq_CodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_app_payload_playviewreq_proto_rawDescGZIP(), []int{0, 0}
}

type PlayViewReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EpId            *int64                 `protobuf:"varint,1,opt,name=epId" json:"epId,omitempty"`
	Cid             *int64                 `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Qn              *int64                 `protobuf:"varint,3,opt,name=qn" json:"qn,omitempty"`
	Fnver           *int32                 `protobuf:"varint,4,opt,name=fnver" json:"fnver,omitempty"`
	Fnval           *int32                 `protobuf:"varint,5,opt,name=fnval" json:"fnval,omitempty"`
	Download        *uint32                `protobuf:"varint,6,opt,name=download" json:"download,omitempty"`
	ForceHost       *int32                 `protobuf:"varint,7,opt,name=forceHost" json:"forceHost,omitempty"`
	Fourk           *bool                  `protobuf:"varint,8,opt,name=fourk" json:"fourk,omitempty"`
	Spmid           *string                `protobuf:"bytes,9,opt,name=spmid" json:"spmid,omitempty"`
	FromSpmid       *string                `protobuf:"bytes,10,opt,name=fromSpmid" json:"fromSpmid,omitempty"`
	TeenagersMode   *int32                 `protobuf:"varint,11,opt,name=teenagersMode" json:"teenagersMode,omitempty"`
	PreferCodecType *PlayViewReq_CodeType  `protobuf:"varint,12,opt,name=preferCodecType,enum=bbdown.PlayViewReq_CodeType" json:"preferCodecType,omitempty"`
	IsPreview       *bool                  `protobuf:"varint,13,opt,name=isPreview" json:"isPreview,omitempty"`
	RoomId          *int64                 `protobuf:"varint,14,opt,name=roomId" json:"roomId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayViewReq) Reset() {
	*x = PlayViewReq{}
	mi := &file_proto_app_payload_playviewreq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayViewReq) ProtoMessage() {}

func (x *PlayViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_payload_playviewreq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayViewReq.ProtoReflect.Descriptor instead.
func (*PlayViewReq) Descriptor() ([]byte, []int) {
	return file_proto_app_payload_playviewreq_proto_rawDescGZIP(), []int{0}
}

func (x *PlayViewReq) GetEpId() int64 {
	if x != nil && x.EpId != nil {
		return *x.EpId
	}
	return 0
}

func (x *PlayViewReq) GetCid() int64 {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return 0
}

func (x *PlayViewReq) GetQn() int64 {
	if x != nil && x.Qn != nil {
		return *x.Qn
	}
	return 0
}

func (x *PlayViewReq) GetFnver() int32 {
	if x != nil && x.Fnver != nil {
		return *x.Fnver
	}
	return 0
}

func (x *PlayViewReq) GetFnval() int32 {
	if x != nil && x.Fnval != nil {
		return *x.Fnval
	}
	return 0
}

func (x *PlayViewReq) GetDownload() uint32 {
	if x != nil && x.Download != nil {
		return *x.Download
	}
	return 0
}

func (x *PlayViewReq) GetForceHost() int32 {
	if x != nil && x.ForceHost != nil {
		return *x.ForceHost
	}
	return 0
}

func (x *PlayViewReq) GetFourk() bool {
	if x != nil && x.Fourk != nil {
		return *x.Fourk
	}
	return false
}

func (x *PlayViewReq) GetSpmid() string {
	if x != nil && x.Spmid != nil {
		return *x.Spmid
	}
	return ""
}

func (x *PlayViewReq) GetFromSpmid() string {
	if x != nil && x.FromSpmid != nil {
		return *x.FromSpmid
	}
	return ""
}

func (x *PlayViewReq) GetTeenagersMode() int32 {
	if x != nil && x.TeenagersMode != nil {
		return *x.TeenagersMode
	}
	return 0
}

func (x *PlayViewReq) GetPreferCodecType() PlayViewReq_CodeType {
	if x != nil && x.PreferCodecType != nil {
		return *x.PreferCodecType
	}
	return PlayViewReq_NOCODE
}

func (x *PlayViewReq) GetIsPreview() bool {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return false
}

func (x *PlayViewReq) GetRoomId() int64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

var File_proto_app_payload_playviewreq_proto protoreflect.FileDescriptor

const file_proto_app_payload_playviewreq_proto_rawDesc = "" +
	"\n" +
	"#proto/app/payload/playviewreq.proto\x12\x06bbdown\"\xd6\x03\n" +
	"\vPlayViewReq\x12\x12\n" +
	"\x04epId\x18\x01 \x01(\x03R\x04epId\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x03R\x03cid\x12\x0e\n" +
	"\x02qn\x18\x03 \x01(\x03R\x02qn\x12\x14\n" +
	"\x05fnver\x18\x04 \x01(\x05R\x05fnver\x12\x14\n" +
	"\x05fnval\x18\x05 \x01(\x05R\x05fnval\x12\x1a\n" +
	"\bdownload\x18\x06 \x01(\rR\bdownload\x12\x1c\n" +
	"\tforceHost\x18\a \x01(\x05R\tforceHost\x12\x14\n" +
	"\x05fourk\x18\b \x01(\bR\x05fourk\x12\x14\n" +
	"\x05spmid\x18\t \x01(\tR\x05spmid\x12\x1c\n" +
	"\tfromSpmid\x18\n" +
	" \x01(\tR\tfromSpmid\x12$\n" +
	"\rteenagersMode\x18\v \x01(\x05R\rteenagersMode\x12F\n" +
	"\x0fpreferCodecType\x18\f \x01(\x0e2\x1c.bbdown.PlayViewReq.CodeTypeR\x0fpreferCodecType\x12\x1c\n" +
	"\tisPreview\x18\r \x01(\bR\tisPreview\x12\x16\n" +
	"\x06roomId\x18\x0e \x01(\x03R\x06roomId\"=\n" +
	"\bCodeType\x12\n" +
	"\n" +
	"\x06NOCODE\x10\x00\x12\v\n" +
	"\aCODE264\x10\x01\x12\v\n" +
	"\aCODE265\x10\x02\x12\v\n" +
	"\aCODEAV1\x10\x03B\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_payload_playviewreq_proto_rawDescOnce sync.Once
	file_proto_app_payload_playviewreq_proto_rawDescData []byte
)

func file_proto_app_payload_playviewreq_proto_rawDescGZIP() []byte {
	file_proto_app_payload_playviewreq_proto_rawDescOnce.Do(func() {
		file_proto_app_payload_playviewreq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_payload_playviewreq_proto_rawDesc), len(file_proto_app_payload_playviewreq_proto_rawDesc)))
	})
	return file_proto_app_payload_playviewreq_proto_rawDescData
}

var file_proto_app_payload_playviewreq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_app_payload_playviewreq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_payload_playviewreq_proto_goTypes = []any{
	(PlayViewReq_CodeType)(0), // 0: bbdown.PlayViewReq.CodeType
	(*PlayViewReq)(nil),       // 1: bbdown.PlayViewReq
}
var file_proto_app_payload_playviewreq_proto_depIdxs = []int32{
	0, // 0: bbdown.PlayViewReq.preferCodecType:type_name -> bbdown.PlayViewReq.CodeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_app_payload_playviewreq_proto_init() }
func file_proto_app_payload_playviewreq_proto_init() {
	if File_proto_app_payload_playviewreq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_payload_playviewreq_proto_rawDesc), len(file_proto_app_payload_playviewreq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_payload_playviewreq_proto_goTypes,
		DependencyIndexes: file_proto_app_payload_playviewreq_proto_depIdxs,
		EnumInfos:         file_proto_app_payload_playviewreq_proto_enumTypes,
		MessageInfos:      file_proto_app_payload_playviewreq_proto_msgTypes,
	}.Build()
	File_proto_app_payload_playviewreq_proto = out.File
	file_proto_app_payload_playviewreq_proto_goTypes = nil
	file_proto_app_payload_playviewreq_proto_depIdxs = nil
}
