// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/response/playviewreply.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Quality      *uint32                `protobuf:"varint,1,opt,name=quality" json:"quality,omitempty"`
	Format       *string                `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Timelength   *uint64                `protobuf:"varint,3,opt,name=timelength" json:"timelength,omitempty"`
	VideoCodecid *uint32                `protobuf:"varint,4,opt,name=videoCodecid" json:"videoCodecid,omitempty"`
	StreamList   []*StreamItem          `protobuf:"bytes,5,rep,name=streamList" json:"streamList,omitempty"`
	DashAudio    []*DashItem            `protobuf:"bytes,6,rep,name=dashAudio" json:"dashAudio,omitempty"`
	// 杜比伴音流
	Dolby         *DolbyItem `protobuf:"bytes,7,opt,name=dolby" json:"dolby,omitempty"`
	Flac          *DolbyItem `protobuf:"bytes,9,opt,name=flac" json:"flac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{0}
}

func (x *VideoInfo) GetQuality() uint32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

func (x *VideoInfo) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *VideoInfo) GetTimelength() uint64 {
	if x != nil && x.Timelength != nil {
		return *x.Timelength
	}
	return 0
}

func (x *VideoInfo) GetVideoCodecid() uint32 {
	if x != nil && x.VideoCodecid != nil {
		return *x.VideoCodecid
	}
	return 0
}

func (x *VideoInfo) GetStreamList() []*StreamItem {
	if x != nil {
		return x.StreamList
	}
	return nil
}

func (x *VideoInfo) GetDashAudio() []*DashItem {
	if x != nil {
		return x.DashAudio
	}
	return nil
}

func (x *VideoInfo) GetDolby() *DolbyItem {
	if x != nil {
		return x.Dolby
	}
	return nil
}

func (x *VideoInfo) GetFlac() *DolbyItem {
	if x != nil {
		return x.Flac
	}
	return nil
}

// 杜比音频信息
type DolbyItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  *int32                 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	// 音频流
	Audio         *DashItem `protobuf:"bytes,2,opt,name=audio" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DolbyItem) Reset() {
	*x = DolbyItem{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DolbyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DolbyItem) ProtoMessage() {}

func (x *DolbyItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DolbyItem.ProtoReflect.Descriptor instead.
func (*DolbyItem) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{1}
}

func (x *DolbyItem) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *DolbyItem) GetAudio() *DashItem {
	if x != nil {
		return x.Audio
	}
	return nil
}

type PlayAbilityConf struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BackgroundPlayDisable *bool                  `protobuf:"varint,1,opt,name=backgroundPlayDisable" json:"backgroundPlayDisable,omitempty"`
	FlipDisable           *bool                  `protobuf:"varint,2,opt,name=flipDisable" json:"flipDisable,omitempty"`
	CastDisable           *bool                  `protobuf:"varint,3,opt,name=castDisable" json:"castDisable,omitempty"`
	FeedbackDisable       *bool                  `protobuf:"varint,4,opt,name=feedbackDisable" json:"feedbackDisable,omitempty"`
	SubtitleDisable       *bool                  `protobuf:"varint,5,opt,name=subtitleDisable" json:"subtitleDisable,omitempty"`
	PlaybackRateDisable   *bool                  `protobuf:"varint,6,opt,name=playbackRateDisable" json:"playbackRateDisable,omitempty"`
	TimeUpDisable         *bool                  `protobuf:"varint,7,opt,name=timeUpDisable" json:"timeUpDisable,omitempty"`
	PlaybackModeDisable   *bool                  `protobuf:"varint,8,opt,name=playbackModeDisable" json:"playbackModeDisable,omitempty"`
	ScaleModeDisable      *bool                  `protobuf:"varint,9,opt,name=scaleModeDisable" json:"scaleModeDisable,omitempty"`
	LikeDisable           *bool                  `protobuf:"varint,10,opt,name=likeDisable" json:"likeDisable,omitempty"`
	DislikeDisable        *bool                  `protobuf:"varint,11,opt,name=dislikeDisable" json:"dislikeDisable,omitempty"`
	CoinDisable           *bool                  `protobuf:"varint,12,opt,name=coinDisable" json:"coinDisable,omitempty"`
	ElecDisable           *bool                  `protobuf:"varint,13,opt,name=elecDisable" json:"elecDisable,omitempty"`
	ShareDisable          *bool                  `protobuf:"varint,14,opt,name=shareDisable" json:"shareDisable,omitempty"`
	ScreenShotDisable     *bool                  `protobuf:"varint,15,opt,name=screenShotDisable" json:"screenShotDisable,omitempty"`
	LockScreenDisable     *bool                  `protobuf:"varint,16,opt,name=lockScreenDisable" json:"lockScreenDisable,omitempty"`
	RecommendDisable      *bool                  `protobuf:"varint,17,opt,name=recommendDisable" json:"recommendDisable,omitempty"`
	PlaybackSpeedDisable  *bool                  `protobuf:"varint,18,opt,name=playbackSpeedDisable" json:"playbackSpeedDisable,omitempty"`
	DefinitionDisable     *bool                  `protobuf:"varint,19,opt,name=definitionDisable" json:"definitionDisable,omitempty"`
	SelectionsDisable     *bool                  `protobuf:"varint,20,opt,name=selectionsDisable" json:"selectionsDisable,omitempty"`
	NextDisable           *bool                  `protobuf:"varint,21,opt,name=nextDisable" json:"nextDisable,omitempty"`
	EditDmDisable         *bool                  `protobuf:"varint,22,opt,name=editDmDisable" json:"editDmDisable,omitempty"`
	SmallWindowDisable    *bool                  `protobuf:"varint,23,opt,name=smallWindowDisable" json:"smallWindowDisable,omitempty"`
	ShakeDisable          *bool                  `protobuf:"varint,24,opt,name=shakeDisable" json:"shakeDisable,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayAbilityConf) Reset() {
	*x = PlayAbilityConf{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayAbilityConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayAbilityConf) ProtoMessage() {}

func (x *PlayAbilityConf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayAbilityConf.ProtoReflect.Descriptor instead.
func (*PlayAbilityConf) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{2}
}

func (x *PlayAbilityConf) GetBackgroundPlayDisable() bool {
	if x != nil && x.BackgroundPlayDisable != nil {
		return *x.BackgroundPlayDisable
	}
	return false
}

func (x *PlayAbilityConf) GetFlipDisable() bool {
	if x != nil && x.FlipDisable != nil {
		return *x.FlipDisable
	}
	return false
}

func (x *PlayAbilityConf) GetCastDisable() bool {
	if x != nil && x.CastDisable != nil {
		return *x.CastDisable
	}
	return false
}

func (x *PlayAbilityConf) GetFeedbackDisable() bool {
	if x != nil && x.FeedbackDisable != nil {
		return *x.FeedbackDisable
	}
	return false
}

func (x *PlayAbilityConf) GetSubtitleDisable() bool {
	if x != nil && x.SubtitleDisable != nil {
		return *x.SubtitleDisable
	}
	return false
}

func (x *PlayAbilityConf) GetPlaybackRateDisable() bool {
	if x != nil && x.PlaybackRateDisable != nil {
		return *x.PlaybackRateDisable
	}
	return false
}

func (x *PlayAbilityConf) GetTimeUpDisable() bool {
	if x != nil && x.TimeUpDisable != nil {
		return *x.TimeUpDisable
	}
	return false
}

func (x *PlayAbilityConf) GetPlaybackModeDisable() bool {
	if x != nil && x.PlaybackModeDisable != nil {
		return *x.PlaybackModeDisable
	}
	return false
}

func (x *PlayAbilityConf) GetScaleModeDisable() bool {
	if x != nil && x.ScaleModeDisable != nil {
		return *x.ScaleModeDisable
	}
	return false
}

func (x *PlayAbilityConf) GetLikeDisable() bool {
	if x != nil && x.LikeDisable != nil {
		return *x.LikeDisable
	}
	return false
}

func (x *PlayAbilityConf) GetDislikeDisable() bool {
	if x != nil && x.DislikeDisable != nil {
		return *x.DislikeDisable
	}
	return false
}

func (x *PlayAbilityConf) GetCoinDisable() bool {
	if x != nil && x.CoinDisable != nil {
		return *x.CoinDisable
	}
	return false
}

func (x *PlayAbilityConf) GetElecDisable() bool {
	if x != nil && x.ElecDisable != nil {
		return *x.ElecDisable
	}
	return false
}

func (x *PlayAbilityConf) GetShareDisable() bool {
	if x != nil && x.ShareDisable != nil {
		return *x.ShareDisable
	}
	return false
}

func (x *PlayAbilityConf) GetScreenShotDisable() bool {
	if x != nil && x.ScreenShotDisable != nil {
		return *x.ScreenShotDisable
	}
	return false
}

func (x *PlayAbilityConf) GetLockScreenDisable() bool {
	if x != nil && x.LockScreenDisable != nil {
		return *x.LockScreenDisable
	}
	return false
}

func (x *PlayAbilityConf) GetRecommendDisable() bool {
	if x != nil && x.RecommendDisable != nil {
		return *x.RecommendDisable
	}
	return false
}

func (x *PlayAbilityConf) GetPlaybackSpeedDisable() bool {
	if x != nil && x.PlaybackSpeedDisable != nil {
		return *x.PlaybackSpeedDisable
	}
	return false
}

func (x *PlayAbilityConf) GetDefinitionDisable() bool {
	if x != nil && x.DefinitionDisable != nil {
		return *x.DefinitionDisable
	}
	return false
}

func (x *PlayAbilityConf) GetSelectionsDisable() bool {
	if x != nil && x.SelectionsDisable != nil {
		return *x.SelectionsDisable
	}
	return false
}

func (x *PlayAbilityConf) GetNextDisable() bool {
	if x != nil && x.NextDisable != nil {
		return *x.NextDisable
	}
	return false
}

func (x *PlayAbilityConf) GetEditDmDisable() bool {
	if x != nil && x.EditDmDisable != nil {
		return *x.EditDmDisable
	}
	return false
}

func (x *PlayAbilityConf) GetSmallWindowDisable() bool {
	if x != nil && x.SmallWindowDisable != nil {
		return *x.SmallWindowDisable
	}
	return false
}

func (x *PlayAbilityConf) GetShakeDisable() bool {
	if x != nil && x.ShakeDisable != nil {
		return *x.ShakeDisable
	}
	return false
}

type ClipInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *int32                 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End           *int32                 `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	ToastText     *string                `protobuf:"bytes,5,opt,name=toastText" json:"toastText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipInfo) Reset() {
	*x = ClipInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipInfo) ProtoMessage() {}

func (x *ClipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipInfo.ProtoReflect.Descriptor instead.
func (*ClipInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{3}
}

func (x *ClipInfo) GetStart() int32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *ClipInfo) GetEnd() int32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *ClipInfo) GetToastText() string {
	if x != nil && x.ToastText != nil {
		return *x.ToastText
	}
	return ""
}

type BusinessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPreview     *bool                  `protobuf:"varint,1,opt,name=isPreview" json:"isPreview,omitempty"`
	Bp            *bool                  `protobuf:"varint,2,opt,name=bp" json:"bp,omitempty"`
	MarlinToken   *string                `protobuf:"bytes,3,opt,name=marlinToken" json:"marlinToken,omitempty"`
	ClipInfo      []*ClipInfo            `protobuf:"bytes,6,rep,name=clipInfo" json:"clipInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessInfo) Reset() {
	*x = BusinessInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessInfo) ProtoMessage() {}

func (x *BusinessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessInfo.ProtoReflect.Descriptor instead.
func (*BusinessInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{4}
}

func (x *BusinessInfo) GetIsPreview() bool {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return false
}

func (x *BusinessInfo) GetBp() bool {
	if x != nil && x.Bp != nil {
		return *x.Bp
	}
	return false
}

func (x *BusinessInfo) GetMarlinToken() string {
	if x != nil && x.MarlinToken != nil {
		return *x.MarlinToken
	}
	return ""
}

func (x *BusinessInfo) GetClipInfo() []*ClipInfo {
	if x != nil {
		return x.ClipInfo
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shake         *Shake                 `protobuf:"bytes,1,opt,name=shake" json:"shake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetShake() *Shake {
	if x != nil {
		return x.Shake
	}
	return nil
}

type Shake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *string                `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shake) Reset() {
	*x = Shake{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shake) ProtoMessage() {}

func (x *Shake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shake.ProtoReflect.Descriptor instead.
func (*Shake) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{6}
}

func (x *Shake) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

type DashItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BaseUrl       *string                `protobuf:"bytes,2,opt,name=baseUrl" json:"baseUrl,omitempty"`
	BackupUrl     []string               `protobuf:"bytes,3,rep,name=backupUrl" json:"backupUrl,omitempty"`
	Bandwidth     *uint32                `protobuf:"varint,4,opt,name=bandwidth" json:"bandwidth,omitempty"`
	Codecid       *uint32                `protobuf:"varint,5,opt,name=codecid" json:"codecid,omitempty"`
	Md5           *string                `protobuf:"bytes,6,opt,name=md5" json:"md5,omitempty"`
	Size          *uint64                `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashItem) Reset() {
	*x = DashItem{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashItem) ProtoMessage() {}

func (x *DashItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashItem.ProtoReflect.Descriptor instead.
func (*DashItem) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{7}
}

func (x *DashItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DashItem) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *DashItem) GetBackupUrl() []string {
	if x != nil {
		return x.BackupUrl
	}
	return nil
}

func (x *DashItem) GetBandwidth() uint32 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

func (x *DashItem) GetCodecid() uint32 {
	if x != nil && x.Codecid != nil {
		return *x.Codecid
	}
	return 0
}

func (x *DashItem) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *DashItem) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type StreamItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamInfo    *StreamInfo            `protobuf:"bytes,1,opt,name=streamInfo" json:"streamInfo,omitempty"`
	DashVideo     *DashVideo             `protobuf:"bytes,2,opt,name=dashVideo" json:"dashVideo,omitempty"`
	SegmentVideo  *SegmentVideo          `protobuf:"bytes,3,opt,name=segmentVideo" json:"segmentVideo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamItem) Reset() {
	*x = StreamItem{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamItem) ProtoMessage() {}

func (x *StreamItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamItem.ProtoReflect.Descriptor instead.
func (*StreamItem) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{8}
}

func (x *StreamItem) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

func (x *StreamItem) GetDashVideo() *DashVideo {
	if x != nil {
		return x.DashVideo
	}
	return nil
}

func (x *StreamItem) GetSegmentVideo() *SegmentVideo {
	if x != nil {
		return x.SegmentVideo
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       *uint32                `protobuf:"varint,1,opt,name=quality" json:"quality,omitempty"`
	Format        *string                `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ErrCode       *uint32                `protobuf:"varint,4,opt,name=errCode" json:"errCode,omitempty"`
	Limit         *StreamLimit           `protobuf:"bytes,5,opt,name=limit" json:"limit,omitempty"`
	NeedVip       *bool                  `protobuf:"varint,6,opt,name=needVip" json:"needVip,omitempty"`
	NeedLogin     *bool                  `protobuf:"varint,7,opt,name=needLogin" json:"needLogin,omitempty"`
	Intact        *bool                  `protobuf:"varint,8,opt,name=intact" json:"intact,omitempty"`
	NoRexcode     *bool                  `protobuf:"varint,9,opt,name=noRexcode" json:"noRexcode,omitempty"`
	Attribute     *uint64                `protobuf:"varint,10,opt,name=attribute" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{9}
}

func (x *StreamInfo) GetQuality() uint32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

func (x *StreamInfo) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *StreamInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *StreamInfo) GetErrCode() uint32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *StreamInfo) GetLimit() *StreamLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *StreamInfo) GetNeedVip() bool {
	if x != nil && x.NeedVip != nil {
		return *x.NeedVip
	}
	return false
}

func (x *StreamInfo) GetNeedLogin() bool {
	if x != nil && x.NeedLogin != nil {
		return *x.NeedLogin
	}
	return false
}

func (x *StreamInfo) GetIntact() bool {
	if x != nil && x.Intact != nil {
		return *x.Intact
	}
	return false
}

func (x *StreamInfo) GetNoRexcode() bool {
	if x != nil && x.NoRexcode != nil {
		return *x.NoRexcode
	}
	return false
}

func (x *StreamInfo) GetAttribute() uint64 {
	if x != nil && x.Attribute != nil {
		return *x.Attribute
	}
	return 0
}

type DashVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       *string                `protobuf:"bytes,1,opt,name=baseUrl" json:"baseUrl,omitempty"`
	BackupUrl     []string               `protobuf:"bytes,2,rep,name=backupUrl" json:"backupUrl,omitempty"`
	Bandwidth     *uint32                `protobuf:"varint,3,opt,name=bandwidth" json:"bandwidth,omitempty"`
	Codecid       *uint32                `protobuf:"varint,4,opt,name=codecid" json:"codecid,omitempty"`
	Md5           *string                `protobuf:"bytes,5,opt,name=md5" json:"md5,omitempty"`
	Size          *uint64                `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	AudioId       *uint32                `protobuf:"varint,7,opt,name=audioId" json:"audioId,omitempty"`
	NoRexcode     *bool                  `protobuf:"varint,8,opt,name=noRexcode" json:"noRexcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashVideo) Reset() {
	*x = DashVideo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashVideo) ProtoMessage() {}

func (x *DashVideo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashVideo.ProtoReflect.Descriptor instead.
func (*DashVideo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{10}
}

func (x *DashVideo) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *DashVideo) GetBackupUrl() []string {
	if x != nil {
		return x.BackupUrl
	}
	return nil
}

func (x *DashVideo) GetBandwidth() uint32 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

func (x *DashVideo) GetCodecid() uint32 {
	if x != nil && x.Codecid != nil {
		return *x.Codecid
	}
	return 0
}

func (x *DashVideo) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *DashVideo) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *DashVideo) GetAudioId() uint32 {
	if x != nil && x.AudioId != nil {
		return *x.AudioId
	}
	return 0
}

func (x *DashVideo) GetNoRexcode() bool {
	if x != nil && x.NoRexcode != nil {
		return *x.NoRexcode
	}
	return false
}

type SegmentVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       []*ResponseUrl         `protobuf:"bytes,1,rep,name=segment" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentVideo) Reset() {
	*x = SegmentVideo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentVideo) ProtoMessage() {}

func (x *SegmentVideo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentVideo.ProtoReflect.Descriptor instead.
func (*SegmentVideo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{11}
}

func (x *SegmentVideo) GetSegment() []*ResponseUrl {
	if x != nil {
		return x.Segment
	}
	return nil
}

type StreamLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Uri           *string                `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
	Msg           *string                `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLimit) Reset() {
	*x = StreamLimit{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLimit) ProtoMessage() {}

func (x *StreamLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLimit.ProtoReflect.Descriptor instead.
func (*StreamLimit) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{12}
}

func (x *StreamLimit) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *StreamLimit) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *StreamLimit) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type ResponseUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *uint32                `protobuf:"varint,1,opt,name=order" json:"order,omitempty"`
	Length        *uint64                `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Size          *uint64                `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	BackupUrl     []string               `protobuf:"bytes,5,rep,name=backupUrl" json:"backupUrl,omitempty"`
	Md5           *string                `protobuf:"bytes,6,opt,name=md5" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUrl) Reset() {
	*x = ResponseUrl{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUrl) ProtoMessage() {}

func (x *ResponseUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUrl.ProtoReflect.Descriptor instead.
func (*ResponseUrl) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseUrl) GetOrder() uint32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *ResponseUrl) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ResponseUrl) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ResponseUrl) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ResponseUrl) GetBackupUrl() []string {
	if x != nil {
		return x.BackupUrl
	}
	return nil
}

func (x *ResponseUrl) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

type RoleAudioProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配音列表
	AudioMaterialList []*AudioMaterialProto `protobuf:"bytes,4,rep,name=audioMaterialList" json:"audioMaterialList,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoleAudioProto) Reset() {
	*x = RoleAudioProto{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAudioProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAudioProto) ProtoMessage() {}

func (x *RoleAudioProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAudioProto.ProtoReflect.Descriptor instead.
func (*RoleAudioProto) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{14}
}

func (x *RoleAudioProto) GetAudioMaterialList() []*AudioMaterialProto {
	if x != nil {
		return x.AudioMaterialList
	}
	return nil
}

type AudioMaterialProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       *string                `protobuf:"bytes,1,opt,name=audioId" json:"audioId,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Edition       *string                `protobuf:"bytes,3,opt,name=edition" json:"edition,omitempty"`
	PersonName    *string                `protobuf:"bytes,5,opt,name=personName" json:"personName,omitempty"`
	Audio         []*DashItem            `protobuf:"bytes,7,rep,name=audio" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMaterialProto) Reset() {
	*x = AudioMaterialProto{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMaterialProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMaterialProto) ProtoMessage() {}

func (x *AudioMaterialProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMaterialProto.ProtoReflect.Descriptor instead.
func (*AudioMaterialProto) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{15}
}

func (x *AudioMaterialProto) GetAudioId() string {
	if x != nil && x.AudioId != nil {
		return *x.AudioId
	}
	return ""
}

func (x *AudioMaterialProto) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AudioMaterialProto) GetEdition() string {
	if x != nil && x.Edition != nil {
		return *x.Edition
	}
	return ""
}

func (x *AudioMaterialProto) GetPersonName() string {
	if x != nil && x.PersonName != nil {
		return *x.PersonName
	}
	return ""
}

func (x *AudioMaterialProto) GetAudio() []*DashItem {
	if x != nil {
		return x.Audio
	}
	return nil
}

type PlayDubbingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 背景音频
	BackgroundAudio *AudioMaterialProto `protobuf:"bytes,1,opt,name=backgroundAudio" json:"backgroundAudio,omitempty"`
	// 角色音频列表
	RoleAudioList []*RoleAudioProto `protobuf:"bytes,2,rep,name=roleAudioList" json:"roleAudioList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayDubbingInfo) Reset() {
	*x = PlayDubbingInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayDubbingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDubbingInfo) ProtoMessage() {}

func (x *PlayDubbingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDubbingInfo.ProtoReflect.Descriptor instead.
func (*PlayDubbingInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{16}
}

func (x *PlayDubbingInfo) GetBackgroundAudio() *AudioMaterialProto {
	if x != nil {
		return x.BackgroundAudio
	}
	return nil
}

func (x *PlayDubbingInfo) GetRoleAudioList() []*RoleAudioProto {
	if x != nil {
		return x.RoleAudioList
	}
	return nil
}

type PlayExtInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 播放配音信息
	PlayDubbingInfo *PlayDubbingInfo `protobuf:"bytes,1,opt,name=playDubbingInfo" json:"playDubbingInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayExtInfo) Reset() {
	*x = PlayExtInfo{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayExtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayExtInfo) ProtoMessage() {}

func (x *PlayExtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayExtInfo.ProtoReflect.Descriptor instead.
func (*PlayExtInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{17}
}

func (x *PlayExtInfo) GetPlayDubbingInfo() *PlayDubbingInfo {
	if x != nil {
		return x.PlayDubbingInfo
	}
	return nil
}

type PlayViewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoInfo     *VideoInfo             `protobuf:"bytes,1,opt,name=videoInfo" json:"videoInfo,omitempty"`
	PlayConf      *PlayAbilityConf       `protobuf:"bytes,2,opt,name=playConf" json:"playConf,omitempty"`
	Business      *BusinessInfo          `protobuf:"bytes,3,opt,name=business" json:"business,omitempty"`
	Event         *Event                 `protobuf:"bytes,4,opt,name=event" json:"event,omitempty"`
	PlayExtInfo   *PlayExtInfo           `protobuf:"bytes,7,opt,name=playExtInfo" json:"playExtInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayViewReply) Reset() {
	*x = PlayViewReply{}
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayViewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayViewReply) ProtoMessage() {}

func (x *PlayViewReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_response_playviewreply_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayViewReply.ProtoReflect.Descriptor instead.
func (*PlayViewReply) Descriptor() ([]byte, []int) {
	return file_proto_app_response_playviewreply_proto_rawDescGZIP(), []int{18}
}

func (x *PlayViewReply) GetVideoInfo() *VideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

func (x *PlayViewReply) GetPlayConf() *PlayAbilityConf {
	if x != nil {
		return x.PlayConf
	}
	return nil
}

func (x *PlayViewReply) GetBusiness() *BusinessInfo {
	if x != nil {
		return x.Business
	}
	return nil
}

func (x *PlayViewReply) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PlayViewReply) GetPlayExtInfo() *PlayExtInfo {
	if x != nil {
		return x.PlayExtInfo
	}
	return nil
}

var File_proto_app_response_playviewreply_proto protoreflect.FileDescriptor

const file_proto_app_response_playviewreply_proto_rawDesc = "" +
	"\n" +
	"&proto/app/response/playviewreply.proto\x12\x06bbdown\"\xb5\x02\n" +
	"\tVideoInfo\x12\x18\n" +
	"\aquality\x18\x01 \x01(\rR\aquality\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"timelength\x18\x03 \x01(\x04R\n" +
	"timelength\x12\"\n" +
	"\fvideoCodecid\x18\x04 \x01(\rR\fvideoCodecid\x122\n" +
	"\n" +
	"streamList\x18\x05 \x03(\v2\x12.bbdown.StreamItemR\n" +
	"streamList\x12.\n" +
	"\tdashAudio\x18\x06 \x03(\v2\x10.bbdown.DashItemR\tdashAudio\x12'\n" +
	"\x05dolby\x18\a \x01(\v2\x11.bbdown.DolbyItemR\x05dolby\x12%\n" +
	"\x04flac\x18\t \x01(\v2\x11.bbdown.DolbyItemR\x04flac\"G\n" +
	"\tDolbyItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12&\n" +
	"\x05audio\x18\x02 \x01(\v2\x10.bbdown.DashItemR\x05audio\"\xfb\a\n" +
	"\x0fPlayAbilityConf\x124\n" +
	"\x15backgroundPlayDisable\x18\x01 \x01(\bR\x15backgroundPlayDisable\x12 \n" +
	"\vflipDisable\x18\x02 \x01(\bR\vflipDisable\x12 \n" +
	"\vcastDisable\x18\x03 \x01(\bR\vcastDisable\x12(\n" +
	"\x0ffeedbackDisable\x18\x04 \x01(\bR\x0ffeedbackDisable\x12(\n" +
	"\x0fsubtitleDisable\x18\x05 \x01(\bR\x0fsubtitleDisable\x120\n" +
	"\x13playbackRateDisable\x18\x06 \x01(\bR\x13playbackRateDisable\x12$\n" +
	"\rtimeUpDisable\x18\a \x01(\bR\rtimeUpDisable\x120\n" +
	"\x13playbackModeDisable\x18\b \x01(\bR\x13playbackModeDisable\x12*\n" +
	"\x10scaleModeDisable\x18\t \x01(\bR\x10scaleModeDisable\x12 \n" +
	"\vlikeDisable\x18\n" +
	" \x01(\bR\vlikeDisable\x12&\n" +
	"\x0edislikeDisable\x18\v \x01(\bR\x0edislikeDisable\x12 \n" +
	"\vcoinDisable\x18\f \x01(\bR\vcoinDisable\x12 \n" +
	"\velecDisable\x18\r \x01(\bR\velecDisable\x12\"\n" +
	"\fshareDisable\x18\x0e \x01(\bR\fshareDisable\x12,\n" +
	"\x11screenShotDisable\x18\x0f \x01(\bR\x11screenShotDisable\x12,\n" +
	"\x11lockScreenDisable\x18\x10 \x01(\bR\x11lockScreenDisable\x12*\n" +
	"\x10recommendDisable\x18\x11 \x01(\bR\x10recommendDisable\x122\n" +
	"\x14playbackSpeedDisable\x18\x12 \x01(\bR\x14playbackSpeedDisable\x12,\n" +
	"\x11definitionDisable\x18\x13 \x01(\bR\x11definitionDisable\x12,\n" +
	"\x11selectionsDisable\x18\x14 \x01(\bR\x11selectionsDisable\x12 \n" +
	"\vnextDisable\x18\x15 \x01(\bR\vnextDisable\x12$\n" +
	"\reditDmDisable\x18\x16 \x01(\bR\reditDmDisable\x12.\n" +
	"\x12smallWindowDisable\x18\x17 \x01(\bR\x12smallWindowDisable\x12\"\n" +
	"\fshakeDisable\x18\x18 \x01(\bR\fshakeDisable\"P\n" +
	"\bClipInfo\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x1c\n" +
	"\ttoastText\x18\x05 \x01(\tR\ttoastText\"\x8c\x01\n" +
	"\fBusinessInfo\x12\x1c\n" +
	"\tisPreview\x18\x01 \x01(\bR\tisPreview\x12\x0e\n" +
	"\x02bp\x18\x02 \x01(\bR\x02bp\x12 \n" +
	"\vmarlinToken\x18\x03 \x01(\tR\vmarlinToken\x12,\n" +
	"\bclipInfo\x18\x06 \x03(\v2\x10.bbdown.ClipInfoR\bclipInfo\",\n" +
	"\x05Event\x12#\n" +
	"\x05shake\x18\x01 \x01(\v2\r.bbdown.ShakeR\x05shake\"\x1b\n" +
	"\x05Shake\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\"\xb0\x01\n" +
	"\bDashItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\abaseUrl\x18\x02 \x01(\tR\abaseUrl\x12\x1c\n" +
	"\tbackupUrl\x18\x03 \x03(\tR\tbackupUrl\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\rR\tbandwidth\x12\x18\n" +
	"\acodecid\x18\x05 \x01(\rR\acodecid\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04size\"\xab\x01\n" +
	"\n" +
	"StreamItem\x122\n" +
	"\n" +
	"streamInfo\x18\x01 \x01(\v2\x12.bbdown.StreamInfoR\n" +
	"streamInfo\x12/\n" +
	"\tdashVideo\x18\x02 \x01(\v2\x11.bbdown.DashVideoR\tdashVideo\x128\n" +
	"\fsegmentVideo\x18\x03 \x01(\v2\x14.bbdown.SegmentVideoR\fsegmentVideo\"\xb1\x02\n" +
	"\n" +
	"StreamInfo\x12\x18\n" +
	"\aquality\x18\x01 \x01(\rR\aquality\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aerrCode\x18\x04 \x01(\rR\aerrCode\x12)\n" +
	"\x05limit\x18\x05 \x01(\v2\x13.bbdown.StreamLimitR\x05limit\x12\x18\n" +
	"\aneedVip\x18\x06 \x01(\bR\aneedVip\x12\x1c\n" +
	"\tneedLogin\x18\a \x01(\bR\tneedLogin\x12\x16\n" +
	"\x06intact\x18\b \x01(\bR\x06intact\x12\x1c\n" +
	"\tnoRexcode\x18\t \x01(\bR\tnoRexcode\x12\x1c\n" +
	"\tattribute\x18\n" +
	" \x01(\x04R\tattribute\"\xd9\x01\n" +
	"\tDashVideo\x12\x18\n" +
	"\abaseUrl\x18\x01 \x01(\tR\abaseUrl\x12\x1c\n" +
	"\tbackupUrl\x18\x02 \x03(\tR\tbackupUrl\x12\x1c\n" +
	"\tbandwidth\x18\x03 \x01(\rR\tbandwidth\x12\x18\n" +
	"\acodecid\x18\x04 \x01(\rR\acodecid\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12\x18\n" +
	"\aaudioId\x18\a \x01(\rR\aaudioId\x12\x1c\n" +
	"\tnoRexcode\x18\b \x01(\bR\tnoRexcode\"=\n" +
	"\fSegmentVideo\x12-\n" +
	"\asegment\x18\x01 \x03(\v2\x13.bbdown.ResponseUrlR\asegment\"G\n" +
	"\vStreamLimit\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x91\x01\n" +
	"\vResponseUrl\x12\x14\n" +
	"\x05order\x18\x01 \x01(\rR\x05order\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1c\n" +
	"\tbackupUrl\x18\x05 \x03(\tR\tbackupUrl\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\"Z\n" +
	"\x0eRoleAudioProto\x12H\n" +
	"\x11audioMaterialList\x18\x04 \x03(\v2\x1a.bbdown.AudioMaterialProtoR\x11audioMaterialList\"\xa6\x01\n" +
	"\x12AudioMaterialProto\x12\x18\n" +
	"\aaudioId\x18\x01 \x01(\tR\aaudioId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aedition\x18\x03 \x01(\tR\aedition\x12\x1e\n" +
	"\n" +
	"personName\x18\x05 \x01(\tR\n" +
	"personName\x12&\n" +
	"\x05audio\x18\a \x03(\v2\x10.bbdown.DashItemR\x05audio\"\x95\x01\n" +
	"\x0fPlayDubbingInfo\x12D\n" +
	"\x0fbackgroundAudio\x18\x01 \x01(\v2\x1a.bbdown.AudioMaterialProtoR\x0fbackgroundAudio\x12<\n" +
	"\rroleAudioList\x18\x02 \x03(\v2\x16.bbdown.RoleAudioProtoR\rroleAudioList\"P\n" +
	"\vPlayExtInfo\x12A\n" +
	"\x0fplayDubbingInfo\x18\x01 \x01(\v2\x17.bbdown.PlayDubbingInfoR\x0fplayDubbingInfo\"\x83\x02\n" +
	"\rPlayViewReply\x12/\n" +
	"\tvideoInfo\x18\x01 \x01(\v2\x11.bbdown.VideoInfoR\tvideoInfo\x123\n" +
	"\bplayConf\x18\x02 \x01(\v2\x17.bbdown.PlayAbilityConfR\bplayConf\x120\n" +
	"\bbusiness\x18\x03 \x01(\v2\x14.bbdown.BusinessInfoR\bbusiness\x12#\n" +
	"\x05event\x18\x04 \x01(\v2\r.bbdown.EventR\x05event\x125\n" +
	"\vplayExtInfo\x18\a \x01(\v2\x13.bbdown.PlayExtInfoR\vplayExtInfoB\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_response_playviewreply_proto_rawDescOnce sync.Once
	file_proto_app_response_playviewreply_proto_rawDescData []byte
)

func file_proto_app_response_playviewreply_proto_rawDescGZIP() []byte {
	file_proto_app_response_playviewreply_proto_rawDescOnce.Do(func() {
		file_proto_app_response_playviewreply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_response_playviewreply_proto_rawDesc), len(file_proto_app_response_playviewreply_proto_rawDesc)))
	})
	return file_proto_app_response_playviewreply_proto_rawDescData
}

var file_proto_app_response_playviewreply_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_app_response_playviewreply_proto_goTypes = []any{
	(*VideoInfo)(nil),          // 0: bbdown.VideoInfo
	(*DolbyItem)(nil),          // 1: bbdown.DolbyItem
	(*PlayAbilityConf)(nil),    // 2: bbdown.PlayAbilityConf
	(*ClipInfo)(nil),           // 3: bbdown.ClipInfo
	(*BusinessInfo)(nil),       // 4: bbdown.BusinessInfo
	(*Event)(nil),              // 5: bbdown.Event
	(*Shake)(nil),              // 6: bbdown.Shake
	(*DashItem)(nil),           // 7: bbdown.DashItem
	(*StreamItem)(nil),         // 8: bbdown.StreamItem
	(*StreamInfo)(nil),         // 9: bbdown.StreamInfo
	(*DashVideo)(nil),          // 10: bbdown.DashVideo
	(*SegmentVideo)(nil),       // 11: bbdown.SegmentVideo
	(*StreamLimit)(nil),        // 12: bbdown.StreamLimit
	(*ResponseUrl)(nil),        // 13: bbdown.ResponseUrl
	(*RoleAudioProto)(nil),     // 14: bbdown.RoleAudioProto
	(*AudioMaterialProto)(nil), // 15: bbdown.AudioMaterialProto
	(*PlayDubbingInfo)(nil),    // 16: bbdown.PlayDubbingInfo
	(*PlayExtInfo)(nil),        // 17: bbdown.PlayExtInfo
	(*PlayViewReply)(nil),      // 18: bbdown.PlayViewReply
}
var file_proto_app_response_playviewreply_proto_depIdxs = []int32{
	8,  // 0: bbdown.VideoInfo.streamList:type_name -> bbdown.StreamItem
	7,  // 1: bbdown.VideoInfo.dashAudio:type_name -> bbdown.DashItem
	1,  // 2: bbdown.VideoInfo.dolby:type_name -> bbdown.DolbyItem
	1,  // 3: bbdown.VideoInfo.flac:type_name -> bbdown.DolbyItem
	7,  // 4: bbdown.DolbyItem.audio:type_name -> bbdown.DashItem
	3,  // 5: bbdown.BusinessInfo.clipInfo:type_name -> bbdown.ClipInfo
	6,  // 6: bbdown.Event.shake:type_name -> bbdown.Shake
	9,  // 7: bbdown.StreamItem.streamInfo:type_name -> bbdown.StreamInfo
	10, // 8: bbdown.StreamItem.dashVideo:type_name -> bbdown.DashVideo
	11, // 9: bbdown.StreamItem.segmentVideo:type_name -> bbdown.SegmentVideo
	12, // 10: bbdown.StreamInfo.limit:type_name -> bbdown.StreamLimit
	13, // 11: bbdown.SegmentVideo.segment:type_name -> bbdown.ResponseUrl
	15, // 12: bbdown.RoleAudioProto.audioMaterialList:type_name -> bbdown.AudioMaterialProto
	7,  // 13: bbdown.AudioMaterialProto.audio:type_name -> bbdown.DashItem
	15, // 14: bbdown.PlayDubbingInfo.backgroundAudio:type_name -> bbdown.AudioMaterialProto
	14, // 15: bbdown.PlayDubbingInfo.roleAudioList:type_name -> bbdown.RoleAudioProto
	16, // 16: bbdown.PlayExtInfo.playDubbingInfo:type_name -> bbdown.PlayDubbingInfo
	0,  // 17: bbdown.PlayViewReply.videoInfo:type_name -> bbdown.VideoInfo
	2,  // 18: bbdown.PlayViewReply.playConf:type_name -> bbdown.PlayAbilityConf
	4,  // 19: bbdown.PlayViewReply.business:type_name -> bbdown.BusinessInfo
	5,  // 20: bbdown.PlayViewReply.event:type_name -> bbdown.Event
	17, // 21: bbdown.PlayViewReply.playExtInfo:type_name -> bbdown.PlayExtInfo
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_app_response_playviewreply_proto_init() }
func file_proto_app_response_playviewreply_proto_init() {
	if File_proto_app_response_playviewreply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_response_playviewreply_proto_rawDesc), len(file_proto_app_response_playviewreply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_response_playviewreply_proto_goTypes,
		DependencyIndexes: file_proto_app_response_playviewreply_proto_depIdxs,
		MessageInfos:      file_proto_app_response_playviewreply_proto_msgTypes,
	}.Build()
	File_proto_app_response_playviewreply_proto = out.File
	file_proto_app_response_playviewreply_proto_goTypes = nil
	file_proto_app_response_playviewreply_proto_depIdxs = nil
}
