// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app/header/restriction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Restriction_Mode int32

const (
	Restriction_NORMAL    Restriction_Mode = 0
	Restriction_TEENAGERS Restriction_Mode = 1
	Restriction_LESSONS   Restriction_Mode = 2
)

// Enum value maps for Restriction_Mode.
var (
	Restriction_Mode_name = map[int32]string{
		0: "NORMAL",
		1: "TEENAGERS",
		2: "LESSONS",
	}
	Restriction_Mode_value = map[string]int32{
		"NORMAL":    0,
		"TEENAGERS": 1,
		"LESSONS":   2,
	}
)

func (x Restriction_Mode) Enum() *Restriction_Mode {
	p := new(Restriction_Mode)
	*p = x
	return p
}

func (x Restriction_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Restriction_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_app_header_restriction_proto_enumTypes[0].Descriptor()
}

func (Restriction_Mode) Type() protoreflect.EnumType {
	return &file_proto_app_header_restriction_proto_enumTypes[0]
}

func (x Restriction_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Restriction_Mode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Restriction_Mode(num)
	return nil
}

// Deprecated: Use Restriction_Mode.Descriptor instead.
func (Restriction_Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_app_header_restriction_proto_rawDescGZIP(), []int{0, 0}
}

type Restriction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeenagersMode *bool                  `protobuf:"varint,1,opt,name=teenagersMode" json:"teenagersMode,omitempty"`
	LessonsMode   *bool                  `protobuf:"varint,2,opt,name=lessonsMode" json:"lessonsMode,omitempty"`
	Mode          *Restriction_Mode      `protobuf:"varint,3,opt,name=mode,enum=bbdown.Restriction_Mode" json:"mode,omitempty"`
	Review        *bool                  `protobuf:"varint,4,opt,name=review" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restriction) Reset() {
	*x = Restriction{}
	mi := &file_proto_app_header_restriction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restriction) ProtoMessage() {}

func (x *Restriction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_header_restriction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restriction.ProtoReflect.Descriptor instead.
func (*Restriction) Descriptor() ([]byte, []int) {
	return file_proto_app_header_restriction_proto_rawDescGZIP(), []int{0}
}

func (x *Restriction) GetTeenagersMode() bool {
	if x != nil && x.TeenagersMode != nil {
		return *x.TeenagersMode
	}
	return false
}

func (x *Restriction) GetLessonsMode() bool {
	if x != nil && x.LessonsMode != nil {
		return *x.LessonsMode
	}
	return false
}

func (x *Restriction) GetMode() Restriction_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return Restriction_NORMAL
}

func (x *Restriction) GetReview() bool {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return false
}

var File_proto_app_header_restriction_proto protoreflect.FileDescriptor

const file_proto_app_header_restriction_proto_rawDesc = "" +
	"\n" +
	"\"proto/app/header/restriction.proto\x12\x06bbdown\"\xcb\x01\n" +
	"\vRestriction\x12$\n" +
	"\rteenagersMode\x18\x01 \x01(\bR\rteenagersMode\x12 \n" +
	"\vlessonsMode\x18\x02 \x01(\bR\vlessonsMode\x12,\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x18.bbdown.Restriction.ModeR\x04mode\x12\x16\n" +
	"\x06review\x18\x04 \x01(\bR\x06review\".\n" +
	"\x04Mode\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\r\n" +
	"\tTEENAGERS\x10\x01\x12\v\n" +
	"\aLESSONS\x10\x02B\x1aZ\x18bbdown-go/internal/pb;pb"

var (
	file_proto_app_header_restriction_proto_rawDescOnce sync.Once
	file_proto_app_header_restriction_proto_rawDescData []byte
)

func file_proto_app_header_restriction_proto_rawDescGZIP() []byte {
	file_proto_app_header_restriction_proto_rawDescOnce.Do(func() {
		file_proto_app_header_restriction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_header_restriction_proto_rawDesc), len(file_proto_app_header_restriction_proto_rawDesc)))
	})
	return file_proto_app_header_restriction_proto_rawDescData
}

var file_proto_app_header_restriction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_app_header_restriction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_app_header_restriction_proto_goTypes = []any{
	(Restriction_Mode)(0), // 0: bbdown.Restriction.Mode
	(*Restriction)(nil),   // 1: bbdown.Restriction
}
var file_proto_app_header_restriction_proto_depIdxs = []int32{
	0, // 0: bbdown.Restriction.mode:type_name -> bbdown.Restriction.Mode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_app_header_restriction_proto_init() }
func file_proto_app_header_restriction_proto_init() {
	if File_proto_app_header_restriction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_header_restriction_proto_rawDesc), len(file_proto_app_header_restriction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_header_restriction_proto_goTypes,
		DependencyIndexes: file_proto_app_header_restriction_proto_depIdxs,
		EnumInfos:         file_proto_app_header_restriction_proto_enumTypes,
		MessageInfos:      file_proto_app_header_restriction_proto_msgTypes,
	}.Build()
	File_proto_app_header_restriction_proto = out.File
	file_proto_app_header_restriction_proto_goTypes = nil
	file_proto_app_header_restriction_proto_depIdxs = nil
}
